"""
Generate categorical AIPW reference values using delicatessen stacked M-estimation.

3-arm treatment (a, b, c) with multinomial propensity and continuous outcome.

DGP:
    L ~ N(0, 1)
    P(A=a|L) = softmax(0, 0.3+0.5L, -0.2+0.3L)[1]  (reference = "a")
    P(A=b|L) = softmax(...)[2]
    P(A=c|L) = softmax(...)[3]
    Y = 2 + 3*(A=="b") + 5*(A=="c") + 1.5*L + eps, eps ~ N(0,1)
    True ATE(b vs a) = 3, True ATE(c vs a) = 5

The fixture CSV is generated by an R script and must exist before running.

Usage:
    cd data-raw
    Rscript -e '
      set.seed(42); n <- 5000; L <- rnorm(n)
      eta_b <- 0.3 + 0.5 * L; eta_c <- -0.2 + 0.3 * L
      denom <- 1 + exp(eta_b) + exp(eta_c)
      p_a <- 1/denom; p_b <- exp(eta_b)/denom; p_c <- exp(eta_c)/denom
      A <- sapply(seq_len(n), function(i) sample(c("a","b","c"), 1, prob=c(p_a[i],p_b[i],p_c[i])))
      Y <- 2 + 3*(A=="b") + 5*(A=="c") + 1.5*L + rnorm(n)
      write.csv(data.frame(Y=Y, A=A, L=L), "aipw_fixture_categorical.csv", row.names=FALSE)
    '
    zepid_venv/bin/python aipw_categorical_reference.py
"""

import numpy as np
import pandas as pd
from scipy.special import softmax as scipy_softmax
from delicatessen import MEstimator


def aipw_categorical(data):
    """
    AIPW for 3-arm categorical treatment via stacked M-estimation.

    Treatment levels: a (reference), b, c.
    Outcome model: Y = beta0 + beta_b * I(A=b) + beta_c * I(A=c) + beta_L * L.
    Propensity: multinomial logit with reference "a":
        log(P(b|L)/P(a|L)) = alpha_b0 + alpha_b1 * L
        log(P(c|L)/P(a|L)) = alpha_c0 + alpha_c1 * L

    EE system:
      1. Outcome model (4 params): X' (Y - X beta)
      2. Propensity model (4 params): multinomial score
      3. AIPW plug-in for a=b: mu_b
      4. AIPW plug-in for a=a: mu_a
      5. AIPW plug-in for a=c: mu_c
    """
    n = len(data)
    Y = data["Y"].values
    A = data["A"].values
    L = data["L"].values

    # Indicators
    I_b = (A == "b").astype(float)
    I_c = (A == "c").astype(float)
    I_a = (A == "a").astype(float)

    # Outcome model design: [1, I(A=b), I(A=c), L]
    X = np.column_stack([np.ones(n), I_b, I_c, L])
    p_beta = X.shape[1]

    # Counterfactual design matrices
    X_set_a = np.column_stack([np.ones(n), np.zeros(n), np.zeros(n), L])
    X_set_b = np.column_stack([np.ones(n), np.ones(n), np.zeros(n), L])
    X_set_c = np.column_stack([np.ones(n), np.zeros(n), np.ones(n), L])

    # Propensity model design: [1, L] for each of (b vs a) and (c vs a)
    Z = np.column_stack([np.ones(n), L])
    p_z = Z.shape[1]
    # 4 propensity params: alpha_b = (alpha_b0, alpha_b1), alpha_c = (alpha_c0, alpha_c1)
    p_alpha = 2 * p_z

    # theta layout:
    #  [0:p_beta]                    = beta (outcome)
    #  [p_beta:p_beta+p_alpha]       = alpha (propensity: alpha_b then alpha_c)
    #  [p_beta+p_alpha]              = mu_b
    #  [p_beta+p_alpha+1]            = mu_a
    #  [p_beta+p_alpha+2]            = mu_c

    def psi(theta):
        beta = theta[:p_beta]
        alpha_b = theta[p_beta:p_beta + p_z]
        alpha_c = theta[p_beta + p_z:p_beta + p_alpha]
        mu_b = theta[p_beta + p_alpha]
        mu_a = theta[p_beta + p_alpha + 1]
        mu_c = theta[p_beta + p_alpha + 2]

        # -- Outcome model EE --
        eta_y = X @ beta
        ee_outcome = X.T * (Y - eta_y)

        # -- Propensity model EE (multinomial logit score) --
        # log-odds: eta_b = Z alpha_b, eta_c = Z alpha_c
        eta_b = Z @ alpha_b
        eta_c = Z @ alpha_c
        # Softmax: P(a), P(b), P(c)
        denom = 1.0 + np.exp(eta_b) + np.exp(eta_c)
        p_a = 1.0 / denom
        p_b_hat = np.exp(eta_b) / denom
        p_c_hat = np.exp(eta_c) / denom

        # Multinomial logit score for b: Z' (I(A=b) - p_b)
        ee_alpha_b = Z.T * (I_b - p_b_hat)
        # Multinomial logit score for c: Z' (I(A=c) - p_c)
        ee_alpha_c = Z.T * (I_c - p_c_hat)

        # -- AIPW plug-ins --
        m_obs = X @ beta
        resid = Y - m_obs

        # For A=b: mu_b = E[m(b,L) + I(A=b)/P(A=b|L) * (Y - m(A,L))]
        m_set_b = X_set_b @ beta
        aipw_b = m_set_b + (I_b / p_b_hat) * resid - mu_b

        # For A=a: mu_a = E[m(a,L) + I(A=a)/P(A=a|L) * (Y - m(A,L))]
        m_set_a = X_set_a @ beta
        aipw_a = m_set_a + (I_a / p_a) * resid - mu_a

        # For A=c: mu_c = E[m(c,L) + I(A=c)/P(A=c|L) * (Y - m(A,L))]
        m_set_c = X_set_c @ beta
        aipw_c = m_set_c + (I_c / p_c_hat) * resid - mu_c

        return np.vstack([
            ee_outcome,      # 4 rows
            ee_alpha_b,      # 2 rows
            ee_alpha_c,      # 2 rows
            aipw_b[np.newaxis, :],   # 1 row
            aipw_a[np.newaxis, :],   # 1 row
            aipw_c[np.newaxis, :],   # 1 row
        ])

    # Initial values
    from numpy.linalg import lstsq
    from scipy.optimize import minimize

    init_beta = lstsq(X, Y, rcond=None)[0]

    # Multinomial logit init via separate logistic regressions
    def nll_logistic(b, Xd, yd):
        p = 1.0 / (1.0 + np.exp(-Xd @ b))
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(yd * np.log(p) + (1 - yd) * np.log(1 - p))

    res_b = minimize(nll_logistic, np.zeros(p_z), args=(Z, I_b), method="BFGS")
    res_c = minimize(nll_logistic, np.zeros(p_z), args=(Z, I_c), method="BFGS")
    init_alpha_b = res_b.x
    init_alpha_c = res_c.x

    # Compute initial propensity predictions
    eta_b_init = Z @ init_alpha_b
    eta_c_init = Z @ init_alpha_c
    denom_init = 1.0 + np.exp(eta_b_init) + np.exp(eta_c_init)
    p_a_init = 1.0 / denom_init
    p_b_init = np.exp(eta_b_init) / denom_init
    p_c_init = np.exp(eta_c_init) / denom_init

    m_obs_init = X @ init_beta
    resid_init = Y - m_obs_init

    mu_b_init = np.mean(X_set_b @ init_beta + (I_b / p_b_init) * resid_init)
    mu_a_init = np.mean(X_set_a @ init_beta + (I_a / p_a_init) * resid_init)
    mu_c_init = np.mean(X_set_c @ init_beta + (I_c / p_c_init) * resid_init)

    init = np.concatenate([
        init_beta, init_alpha_b, init_alpha_c,
        [mu_b_init, mu_a_init, mu_c_init]
    ])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    params = mest.theta
    vcov = mest.variance

    idx_b = p_beta + p_alpha
    idx_a = p_beta + p_alpha + 1
    idx_c = p_beta + p_alpha + 2

    mu_b = params[idx_b]
    mu_a = params[idx_a]
    mu_c = params[idx_c]

    se_b = np.sqrt(vcov[idx_b, idx_b])
    se_a = np.sqrt(vcov[idx_a, idx_a])
    se_c = np.sqrt(vcov[idx_c, idx_c])

    ate_ba = mu_b - mu_a
    var_ba = vcov[idx_b, idx_b] + vcov[idx_a, idx_a] - 2 * vcov[idx_b, idx_a]
    se_ba = np.sqrt(var_ba)

    ate_ca = mu_c - mu_a
    var_ca = vcov[idx_c, idx_c] + vcov[idx_a, idx_a] - 2 * vcov[idx_c, idx_a]
    se_ca = np.sqrt(var_ca)

    return {
        "mu_a": mu_a, "se_a": se_a,
        "mu_b": mu_b, "se_b": se_b,
        "mu_c": mu_c, "se_c": se_c,
        "ate_ba": ate_ba, "se_ba": se_ba,
        "ate_ca": ate_ca, "se_ca": se_ca,
    }


if __name__ == "__main__":
    import os

    print("=" * 60)
    print("Categorical AIPW reference values via delicatessen")
    print("=" * 60)

    fixture_dir = os.path.dirname(os.path.abspath(__file__))
    csv_path = os.path.join(fixture_dir, "aipw_fixture_categorical.csv")

    if not os.path.exists(csv_path):
        print(f"Fixture not found at {csv_path}.")
        print("Generate it with:")
        print("  Rscript -e '<see docstring>'")
        raise SystemExit(1)

    df = pd.read_csv(csv_path)
    print(f"Loaded {len(df)} rows from {csv_path}")
    print(f"Treatment distribution: {dict(df['A'].value_counts())}")

    res = aipw_categorical(df)

    print(f"\n--- Results ---")
    print(f"  mu_a    = {res['mu_a']:.6f}, se_a    = {res['se_a']:.6f}")
    print(f"  mu_b    = {res['mu_b']:.6f}, se_b    = {res['se_b']:.6f}")
    print(f"  mu_c    = {res['mu_c']:.6f}, se_c    = {res['se_c']:.6f}")
    print(f"  ATE(b-a)= {res['ate_ba']:.6f}, se(b-a) = {res['se_ba']:.6f}")
    print(f"  ATE(c-a)= {res['ate_ca']:.6f}, se(c-a) = {res['se_ca']:.6f}")

    print(f"\n# Paste into test-delicatessen-extended.R:")
    print(f"ref_mu_a   <- {res['mu_a']:.4f}")
    print(f"ref_se_a   <- {res['se_a']:.4f}")
    print(f"ref_mu_b   <- {res['mu_b']:.4f}")
    print(f"ref_se_b   <- {res['se_b']:.4f}")
    print(f"ref_ate_ba <- {res['ate_ba']:.4f}")
    print(f"ref_se_ba  <- {res['se_ba']:.4f}")
    print(f"ref_ate_ca <- {res['ate_ca']:.4f}")
    print(f"ref_se_ca  <- {res['se_ca']:.4f}")
