"""
Generate AIPW reference values using delicatessen stacked M-estimation.

Implements the stacked estimating-equation AIPW (Robins, Rotnitzky & Zhao
1994; Zivich et al. 2024) for a binary treatment DGP.

DGP:
    L ~ N(0, 1)
    A | L ~ Bernoulli(expit(0.3 + 0.5 * L))
    Y = 2 + 3*A + 1.5*L + eps,  eps ~ N(0, 1)
    True ATE = E[Y(1)] - E[Y(0)] = 3

Usage:
    cd data-raw
    zepid_venv/bin/python aipw_reference.py

The fixture CSV (aipw_fixture.csv) is generated by the R script
generate_aipw_fixtures.R and must exist before running this script.

Output: prints reference values to paste into test-aipw.R.
"""

import numpy as np
import pandas as pd
from scipy.special import expit
from delicatessen import MEstimator


def aipw_binary_treatment(data):
    """
    AIPW for binary treatment with stacked M-estimation sandwich variance.

    EE system (3 blocks):
      1. Outcome model: s_beta(Y, A, L; beta) = X' (Y - X beta)
         where X = [1, A, L].
      2. Propensity model: s_alpha(A, L; alpha) = Z' (A - expit(Z alpha))
         where Z = [1, L].
      3. AIPW plug-in for a=1:
         omega_1 = m_beta(1, L) + (A / pi(L)) * (Y - m_beta(A, L)) - mu_1
      4. AIPW plug-in for a=0:
         omega_0 = m_beta(0, L) + ((1-A) / (1-pi(L))) * (Y - m_beta(A, L)) - mu_0

    Parameters
    ----------
    data : DataFrame
        Columns: Y, A, L.

    Returns
    -------
    dict with mu_1, se_1, mu_0, se_0, ate, se_ate.
    """
    n = len(data)
    Y = data["Y"].values
    A = data["A"].values.astype(float)
    L = data["L"].values

    # Outcome model design matrix: [1, A, L]
    X = np.column_stack([np.ones(n), A, L])
    p_beta = X.shape[1]

    # Propensity model design matrix: [1, L]
    Z = np.column_stack([np.ones(n), L])
    p_alpha = Z.shape[1]

    # Counterfactual design matrices
    X_a1 = np.column_stack([np.ones(n), np.ones(n), L])
    X_a0 = np.column_stack([np.ones(n), np.zeros(n), L])

    def psi(theta):
        beta = theta[:p_beta]
        alpha = theta[p_beta:p_beta + p_alpha]
        mu_1 = theta[p_beta + p_alpha]
        mu_0 = theta[p_beta + p_alpha + 1]

        # -- Outcome model EE: X' (Y - X beta) --
        eta = X @ beta
        ee_outcome = X.T * (Y - eta)

        # -- Propensity model EE: Z' (A - expit(Z alpha)) --
        pi_hat = expit(Z @ alpha)
        ee_propensity = Z.T * (A - pi_hat)

        # -- AIPW plug-in for a=1 --
        m_a1 = X_a1 @ beta
        m_obs = X @ beta
        resid = Y - m_obs
        aipw_a1 = m_a1 + (A / pi_hat) * resid - mu_1

        # -- AIPW plug-in for a=0 --
        m_a0 = X_a0 @ beta
        aipw_a0 = m_a0 + ((1.0 - A) / (1.0 - pi_hat)) * resid - mu_0

        return np.vstack([
            ee_outcome,
            ee_propensity,
            aipw_a1[np.newaxis, :],
            aipw_a0[np.newaxis, :],
        ])

    # Initial values from OLS and logistic regression
    from numpy.linalg import lstsq
    from scipy.optimize import minimize

    init_beta = lstsq(X, Y, rcond=None)[0]

    def nll_logistic(b, Xd, yd):
        p = expit(Xd @ b)
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(yd * np.log(p) + (1 - yd) * np.log(1 - p))

    res_alpha = minimize(nll_logistic, np.zeros(p_alpha), args=(Z, A),
                         method="BFGS")
    init_alpha = res_alpha.x

    m_a1_init = X_a1 @ init_beta
    m_a0_init = X_a0 @ init_beta
    pi_init = expit(Z @ init_alpha)
    resid_init = Y - X @ init_beta

    mu_1_init = np.mean(m_a1_init + (A / pi_init) * resid_init)
    mu_0_init = np.mean(m_a0_init + ((1 - A) / (1 - pi_init)) * resid_init)

    init = np.concatenate([init_beta, init_alpha, [mu_1_init, mu_0_init]])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    params = mest.theta
    vcov = mest.variance

    mu_1 = params[p_beta + p_alpha]
    mu_0 = params[p_beta + p_alpha + 1]

    idx_1 = p_beta + p_alpha
    idx_0 = p_beta + p_alpha + 1

    se_1 = np.sqrt(vcov[idx_1, idx_1])
    se_0 = np.sqrt(vcov[idx_0, idx_0])

    ate = mu_1 - mu_0
    var_ate = vcov[idx_1, idx_1] + vcov[idx_0, idx_0] - 2 * vcov[idx_1, idx_0]
    se_ate = np.sqrt(var_ate)

    return {
        "mu_1": mu_1, "se_1": se_1,
        "mu_0": mu_0, "se_0": se_0,
        "ate": ate, "se_ate": se_ate,
    }


def aipw_continuous_shift(data, delta=1.0):
    """
    AIPW with a shift intervention A -> A + delta for a continuous
    treatment with gaussian propensity.

    EE system:
      1. Outcome model: X' (Y - X beta), X = [1, A, L].
      2. Propensity model (gaussian): Z' (A - Z alpha), Z = [1, L].
      3. AIPW plug-in for the shifted intervention:
         omega_shift = m_beta(A+delta, L) +
                       (phi((A - Z alpha)/sigma) / phi((A - delta - Z alpha)/sigma))
                       * (Y - m_beta(A, L)) - mu_shift
         (Jacobian-ratio density weight for a shift MTP.)
      4. AIPW plug-in for the natural value:
         omega_nat = m_beta(A, L) - mu_nat
                   (natural value: W=1, so aipw = m(A,L) = gcomp mean)

    For a gaussian propensity A | L ~ N(mu(L), sigma^2), the density
    ratio g(A-delta|L) / f(A|L) = phi((A-delta - mu(L))/sigma) / phi((A - mu(L))/sigma)
    = exp(-delta*(A - mu(L) - delta/2) / sigma^2).  We compute it
    numerically to mirror how causatr's make_weight_fn works.

    Parameters
    ----------
    data : DataFrame
        Columns: Y, A, L.
    delta : float
        Additive shift.
    """
    n = len(data)
    Y = data["Y"].values
    A = data["A"].values
    L = data["L"].values

    # Outcome model: [1, A, L]
    X = np.column_stack([np.ones(n), A, L])
    p_beta = X.shape[1]

    X_shifted = np.column_stack([np.ones(n), A + delta, L])
    # Natural (observed A): same as X

    # Propensity model (gaussian): [1, L], plus sigma in theta
    Z = np.column_stack([np.ones(n), L])
    p_alpha = Z.shape[1]

    # theta layout:
    #  [0:p_beta]               = beta  (outcome model)
    #  [p_beta:p_beta+p_alpha]  = alpha (propensity mean params)
    #  [p_beta+p_alpha]         = log_sigma  (log of propensity SD)
    #  [p_beta+p_alpha+1]       = mu_shift
    #  [p_beta+p_alpha+2]       = mu_nat

    def psi(theta):
        beta = theta[:p_beta]
        alpha = theta[p_beta:p_beta + p_alpha]
        log_sigma = theta[p_beta + p_alpha]
        sigma = np.exp(log_sigma)
        mu_shift = theta[p_beta + p_alpha + 1]
        mu_nat = theta[p_beta + p_alpha + 2]

        # Outcome EE
        eta = X @ beta
        ee_outcome = X.T * (Y - eta)

        # Propensity EE (gaussian): normal score equations
        mu_a = Z @ alpha
        resid_a = A - mu_a
        ee_alpha = Z.T * resid_a
        # Score for log_sigma from N(mu_a, sigma^2): d/d(log_sigma) of log-lik
        # = sum_i [-1 + (resid_a_i/sigma)^2]
        ee_log_sigma = -1 + (resid_a / sigma) ** 2

        # AIPW for the shifted intervention
        m_shifted = X_shifted @ beta
        m_obs = X @ beta
        resid_y = Y - m_obs

        # Density ratio: f(A - delta | mu_a, sigma) / f(A | mu_a, sigma).
        # For gaussian propensity this equals exp(delta*(A - mu_a - delta/2) / sigma^2).
        # This is the pushforward weight for the shift MTP d(a) = a + delta:
        # W_i = f_d(A_obs_i | L_i) / f(A_obs_i | L_i)
        #     = f(A_obs_i - delta | L_i) / f(A_obs_i | L_i).
        dr_shift = np.exp(delta * (A - mu_a - delta / 2.0) / sigma ** 2)

        aipw_shift = m_shifted + dr_shift * resid_y - mu_shift

        # Natural value: density ratio is 1 (identity intervention)
        aipw_nat = m_obs + 1.0 * resid_y - mu_nat

        return np.vstack([
            ee_outcome,
            ee_alpha,
            ee_log_sigma[np.newaxis, :],
            aipw_shift[np.newaxis, :],
            aipw_nat[np.newaxis, :],
        ])

    from numpy.linalg import lstsq
    from scipy.optimize import minimize

    init_beta = lstsq(X, Y, rcond=None)[0]
    init_alpha = lstsq(Z, A, rcond=None)[0]
    resid_a_init = A - Z @ init_alpha
    init_log_sigma = np.log(np.std(resid_a_init))

    m_shifted_init = X_shifted @ init_beta
    m_obs_init = X @ init_beta
    resid_y_init = Y - m_obs_init
    sigma_init = np.exp(init_log_sigma)
    mu_a_init = Z @ init_alpha
    dr_init = np.exp(delta * (A - mu_a_init - delta / 2.0) / sigma_init ** 2)

    mu_shift_init = np.mean(m_shifted_init + dr_init * resid_y_init)
    mu_nat_init = np.mean(m_obs_init + resid_y_init)  # = mean(Y)

    init = np.concatenate([
        init_beta, init_alpha, [init_log_sigma],
        [mu_shift_init, mu_nat_init]
    ])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    params = mest.theta
    vcov = mest.variance

    idx_shift = p_beta + p_alpha + 1
    idx_nat = p_beta + p_alpha + 2

    mu_shift = params[idx_shift]
    mu_nat = params[idx_nat]
    se_shift = np.sqrt(vcov[idx_shift, idx_shift])
    se_nat = np.sqrt(vcov[idx_nat, idx_nat])

    effect = mu_shift - mu_nat
    var_effect = (vcov[idx_shift, idx_shift] + vcov[idx_nat, idx_nat]
                  - 2 * vcov[idx_shift, idx_nat])
    se_effect = np.sqrt(var_effect)

    return {
        "mu_shift": mu_shift, "se_shift": se_shift,
        "mu_nat": mu_nat, "se_nat": se_nat,
        "effect": effect, "se_effect": se_effect,
    }


if __name__ == "__main__":
    import os

    print("=" * 60)
    print("AIPW reference values via delicatessen")
    print("Robins, Rotnitzky & Zhao (1994); Zivich et al. (2024)")
    print("=" * 60)

    fixture_dir = os.path.dirname(os.path.abspath(__file__))

    # --- Binary treatment DGP ---
    print("\n--- Binary treatment AIPW ---")
    print("DGP: L~N(0,1), A|L~Bern(expit(0.3+0.5L)), Y=2+3A+1.5L+eps")
    print("True ATE = 3, n = 5000, seed = 42")

    df_bin = pd.read_csv(os.path.join(fixture_dir, "aipw_fixture_binary.csv"))
    res_bin = aipw_binary_treatment(df_bin)
    print(f"  mu_1    = {res_bin['mu_1']:.4f}, se_1    = {res_bin['se_1']:.4f}")
    print(f"  mu_0    = {res_bin['mu_0']:.4f}, se_0    = {res_bin['se_0']:.4f}")
    print(f"  ate     = {res_bin['ate']:.4f}, se_ate  = {res_bin['se_ate']:.4f}")

    # --- Continuous treatment DGP ---
    print("\n--- Continuous treatment AIPW (shift delta = 1) ---")
    print("DGP: L~N(0,1), A|L~N(1+L, 1), Y=2+2A+1.5L+eps")
    print("True shift effect = 2 * 1 = 2, n = 5000, seed = 99")

    df_cont = pd.read_csv(
        os.path.join(fixture_dir, "aipw_fixture_continuous.csv")
    )
    res_cont = aipw_continuous_shift(df_cont, delta=1.0)
    print(f"  mu_shift = {res_cont['mu_shift']:.4f}, se_shift = {res_cont['se_shift']:.4f}")
    print(f"  mu_nat   = {res_cont['mu_nat']:.4f}, se_nat   = {res_cont['se_nat']:.4f}")
    print(f"  effect   = {res_cont['effect']:.4f}, se_effect= {res_cont['se_effect']:.4f}")

    print("\n" + "=" * 60)
    print("Paste into test-aipw.R:")
    print("=" * 60)

    print("\n# Binary AIPW — delicatessen reference")
    print(f"ref_mu_1   <- {res_bin['mu_1']:.4f}")
    print(f"ref_se_1   <- {res_bin['se_1']:.4f}")
    print(f"ref_mu_0   <- {res_bin['mu_0']:.4f}")
    print(f"ref_se_0   <- {res_bin['se_0']:.4f}")
    print(f"ref_ate    <- {res_bin['ate']:.4f}")
    print(f"ref_se_ate <- {res_bin['se_ate']:.4f}")

    print("\n# Continuous shift AIPW — delicatessen reference")
    print(f"ref_mu_shift   <- {res_cont['mu_shift']:.4f}")
    print(f"ref_se_shift   <- {res_cont['se_shift']:.4f}")
    print(f"ref_mu_nat     <- {res_cont['mu_nat']:.4f}")
    print(f"ref_se_nat     <- {res_cont['se_nat']:.4f}")
    print(f"ref_effect     <- {res_cont['effect']:.4f}")
    print(f"ref_se_effect  <- {res_cont['se_effect']:.4f}")
