"""
Generate longitudinal SNM g-estimation reference values using delicatessen
stacked M-estimation.

Reads shared fixture data generated by R (data-raw/snm_longitudinal_fixture.csv)
so that R and Python operate on the exact same dataset. This enables tight
tolerance comparisons between causatr and delicatessen.

Backward-sequential g-estimation for 2-period binary-treatment DGP:
  Stage 1: solve E[(A1 - E[A1|L1,A0]) * (Y - psi1*A1)] = 0
  Stage 0: solve E[(A0 - E[A0|L0]) * (Y - psi1*A1 - psi0*A0)] = 0

Usage:
    data-raw/deli_venv/bin/python3 data-raw/snm_longitudinal_reference.py

Output: tests/testthat/fixtures/snm_longitudinal_delicatessen.csv
"""

import os
import csv
import sys
import numpy as np
import pandas as pd
from scipy.special import expit
from delicatessen import MEstimator


def run_longitudinal_snm(data_path):
    df = pd.read_csv(data_path)
    n = len(df)

    L0 = df["L0"].values
    A0 = df["A0"].values.astype(float)
    L1 = df["L1"].values
    A1 = df["A1"].values.astype(float)
    Y = df["Y"].values

    def stacked_ee(theta):
        """
        Stacked EE for backward sequential g-estimation.

        theta layout:
          [0:4]  alpha1 = (intercept, L1, lag1_A, lag1_L) for E[A1|L1,A0,L0]
          [4:6]  alpha0 = (intercept, L0) for logistic E[A0 | L0]
          [6]    psi1 = stage-1 blip intercept
          [7]    psi0 = stage-0 blip intercept

        R's treatment model at stage 1 is A ~ L + lag1_A + lag1_L, which
        in wide format is A1 ~ L1 + A0 + L0. Stage 0 is A ~ L, i.e. A0 ~ L0.
        """
        alpha1 = theta[0:4]
        alpha0 = theta[4:6]
        psi1 = theta[6]
        psi0 = theta[7]

        X1 = np.column_stack([np.ones(n), L1, A0, L0])
        X0 = np.column_stack([np.ones(n), L0])

        p1 = expit(X1 @ alpha1)
        ee_alpha1 = ((A1 - p1)[:, None] * X1).T

        p0 = expit(X0 @ alpha0)
        ee_alpha0 = ((A0 - p0)[:, None] * X0).T

        R1 = A1 - p1
        ee_psi1 = (R1 * (Y - psi1 * A1))[None, :]

        R0 = A0 - p0
        ee_psi0 = (R0 * (Y - psi1 * A1 - psi0 * A0))[None, :]

        return np.vstack([ee_alpha1, ee_alpha0, ee_psi1, ee_psi0])

    from scipy.optimize import minimize
    def nll(b, Xd, yd):
        p = expit(Xd @ b)
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(yd * np.log(p) + (1 - yd) * np.log(1 - p))

    X1 = np.column_stack([np.ones(n), L1, A0, L0])
    X0 = np.column_stack([np.ones(n), L0])
    init_a1 = minimize(nll, np.zeros(4), args=(X1, A1), method="BFGS").x
    init_a0 = minimize(nll, np.zeros(2), args=(X0, A0), method="BFGS").x

    init = np.concatenate([init_a1, init_a0, [3.0, 3.0]])
    mest = MEstimator(stacked_ee, init=init)
    mest.estimate(solver="lm")

    psi1 = mest.theta[6]
    psi0 = mest.theta[7]
    se_psi1 = np.sqrt(mest.variance[6, 6])
    se_psi0 = np.sqrt(mest.variance[7, 7])

    return [
        {"parameter": "stage1_psi_intercept",
         "estimate": psi1, "se": se_psi1},
        {"parameter": "stage0_psi_intercept",
         "estimate": psi0, "se": se_psi0},
    ]


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(script_dir, "snm_longitudinal_fixture.csv")
    output_path = os.path.join(
        script_dir, "..", "tests", "testthat", "fixtures",
        "snm_longitudinal_delicatessen.csv"
    )

    results = run_longitudinal_snm(data_path)

    print("=" * 60)
    print("Longitudinal SNM reference values via delicatessen")
    print("=" * 60)
    for row in results:
        print(f"  {row['parameter']:30s} = {row['estimate']:.8f}"
              f"  (SE = {row['se']:.8f})")

    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(
            f, fieldnames=["parameter", "estimate", "se"])
        writer.writeheader()
        for row in results:
            writer.writerow({
                "parameter": row["parameter"],
                "estimate": f"{row['estimate']:.10f}",
                "se": f"{row['se']:.10f}",
            })

    print(f"\nWrote {output_path}")

    print("\nPaste into test-snm-triangulation.R:")
    for row in results:
        name = row["parameter"]
        print(f"ref_{name} <- {row['estimate']:.6f}")
        print(f"ref_se_{name} <- {row['se']:.6f}")
