"""
Generate longitudinal SNM g-estimation reference values using delicatessen
stacked M-estimation.

Reads shared fixture data generated by R (data-raw/*.csv) so that R and
Python operate on the exact same dataset. This enables tight tolerance
comparisons between causatr and delicatessen.

Three scenarios:
  1. Base: binary treatment, no EM, no TF
  2. TF: binary treatment, no EM, treatment-free model (~L)
  3. TV-EM: binary treatment, time-varying effect modification by M

Usage:
    data-raw/deli_venv/bin/python3 data-raw/snm_longitudinal_reference.py

Output:
  tests/testthat/fixtures/snm_longitudinal_delicatessen.csv
  tests/testthat/fixtures/snm_longitudinal_tf_delicatessen.csv
  tests/testthat/fixtures/snm_longitudinal_tv_em_delicatessen.csv
"""

import os
import csv
import sys
import numpy as np
import pandas as pd
from scipy.special import expit
from delicatessen import MEstimator


def run_longitudinal_snm(data_path):
    df = pd.read_csv(data_path)
    n = len(df)

    L0 = df["L0"].values
    A0 = df["A0"].values.astype(float)
    L1 = df["L1"].values
    A1 = df["A1"].values.astype(float)
    Y = df["Y"].values

    def stacked_ee(theta):
        """
        Stacked EE for backward sequential g-estimation.

        theta layout:
          [0:4]  alpha1 = (intercept, L1, lag1_A, lag1_L) for E[A1|L1,A0,L0]
          [4:6]  alpha0 = (intercept, L0) for logistic E[A0 | L0]
          [6]    psi1 = stage-1 blip intercept
          [7]    psi0 = stage-0 blip intercept

        R's treatment model at stage 1 is A ~ L + lag1_A + lag1_L, which
        in wide format is A1 ~ L1 + A0 + L0. Stage 0 is A ~ L, i.e. A0 ~ L0.
        """
        alpha1 = theta[0:4]
        alpha0 = theta[4:6]
        psi1 = theta[6]
        psi0 = theta[7]

        X1 = np.column_stack([np.ones(n), L1, A0, L0])
        X0 = np.column_stack([np.ones(n), L0])

        p1 = expit(X1 @ alpha1)
        ee_alpha1 = ((A1 - p1)[:, None] * X1).T

        p0 = expit(X0 @ alpha0)
        ee_alpha0 = ((A0 - p0)[:, None] * X0).T

        R1 = A1 - p1
        ee_psi1 = (R1 * (Y - psi1 * A1))[None, :]

        R0 = A0 - p0
        ee_psi0 = (R0 * (Y - psi1 * A1 - psi0 * A0))[None, :]

        return np.vstack([ee_alpha1, ee_alpha0, ee_psi1, ee_psi0])

    from scipy.optimize import minimize
    def nll(b, Xd, yd):
        p = expit(Xd @ b)
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(yd * np.log(p) + (1 - yd) * np.log(1 - p))

    X1 = np.column_stack([np.ones(n), L1, A0, L0])
    X0 = np.column_stack([np.ones(n), L0])
    init_a1 = minimize(nll, np.zeros(4), args=(X1, A1), method="BFGS").x
    init_a0 = minimize(nll, np.zeros(2), args=(X0, A0), method="BFGS").x

    init = np.concatenate([init_a1, init_a0, [3.0, 3.0]])
    mest = MEstimator(stacked_ee, init=init)
    mest.estimate(solver="lm")

    psi1 = mest.theta[6]
    psi0 = mest.theta[7]
    se_psi1 = np.sqrt(mest.variance[6, 6])
    se_psi0 = np.sqrt(mest.variance[7, 7])

    return [
        {"parameter": "stage1_psi_intercept",
         "estimate": psi1, "se": se_psi1},
        {"parameter": "stage0_psi_intercept",
         "estimate": psi0, "se": se_psi0},
    ]


def run_longitudinal_snm_tf(data_path):
    """
    Longitudinal SNM with treatment-free model (~L), no effect modification.

    Same fixture as base case. Joint (beta_k, psi_k) at each stage:
      Stage 1: Z1 = [1, L1], beta1 = (2 params), psi1 = (1 param)
      Stage 0: Z0 = [1, L0], beta0 = (2 params), psi0 = (1 param)

    theta layout (12 params):
      [0:4]   alpha1 = logit E[A1 | 1, L1, A0, L0]
      [4:6]   alpha0 = logit E[A0 | 1, L0]
      [6:8]   beta1  = TF coefficients at stage 1
      [8]     psi1   = stage-1 blip intercept
      [9:11]  beta0  = TF coefficients at stage 0
      [11]    psi0   = stage-0 blip intercept

    Backward transform uses blip only: H0 = Y - psi1 * A1
    """
    df = pd.read_csv(data_path)
    n = len(df)

    L0 = df["L0"].values
    A0 = df["A0"].values.astype(float)
    L1 = df["L1"].values
    A1 = df["A1"].values.astype(float)
    Y = df["Y"].values

    def stacked_ee(theta):
        alpha1 = theta[0:4]
        alpha0 = theta[4:6]
        beta1 = theta[6:8]
        psi1 = theta[8]
        beta0 = theta[9:11]
        psi0 = theta[11]

        # Treatment models (same as base case)
        X1 = np.column_stack([np.ones(n), L1, A0, L0])
        X0 = np.column_stack([np.ones(n), L0])

        p1 = expit(X1 @ alpha1)
        ee_alpha1 = ((A1 - p1)[:, None] * X1).T

        p0 = expit(X0 @ alpha0)
        ee_alpha0 = ((A0 - p0)[:, None] * X0).T

        R1 = A1 - p1
        R0 = A0 - p0

        # Stage 1: joint (beta1, psi1), pseudo-outcome = Y
        Z1 = np.column_stack([np.ones(n), L1])
        resid1 = Y - Z1 @ beta1 - psi1 * A1
        ee_beta1 = (Z1.T * resid1[None, :])
        ee_psi1 = (R1 * resid1)[None, :]

        # Backward transform: H0 = Y - psi1 * A1 (blip only, not TF)
        H0 = Y - psi1 * A1

        # Stage 0: joint (beta0, psi0), pseudo-outcome = H0
        Z0 = np.column_stack([np.ones(n), L0])
        resid0 = H0 - Z0 @ beta0 - psi0 * A0
        ee_beta0 = (Z0.T * resid0[None, :])
        ee_psi0 = (R0 * resid0)[None, :]

        return np.vstack([
            ee_alpha1, ee_alpha0,
            ee_beta1, ee_psi1,
            ee_beta0, ee_psi0
        ])

    from scipy.optimize import minimize
    def nll(b, Xd, yd):
        p = expit(Xd @ b)
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(yd * np.log(p) + (1 - yd) * np.log(1 - p))

    X1 = np.column_stack([np.ones(n), L1, A0, L0])
    X0 = np.column_stack([np.ones(n), L0])
    init_a1 = minimize(nll, np.zeros(4), args=(X1, A1), method="BFGS").x
    init_a0 = minimize(nll, np.zeros(2), args=(X0, A0), method="BFGS").x

    init = np.concatenate([init_a1, init_a0, [0, 0, 3.0, 0, 0, 3.0]])
    mest = MEstimator(stacked_ee, init=init)
    mest.estimate(solver="lm")

    psi1 = mest.theta[8]
    psi0 = mest.theta[11]
    se_psi1 = np.sqrt(mest.variance[8, 8])
    se_psi0 = np.sqrt(mest.variance[11, 11])

    return [
        {"parameter": "stage1_psi_intercept",
         "estimate": psi1, "se": se_psi1},
        {"parameter": "stage0_psi_intercept",
         "estimate": psi0, "se": se_psi0},
    ]


def run_longitudinal_snm_tv_em(data_path):
    """
    Longitudinal SNM with time-varying effect modification by M.

    Blip: gamma_k = A_k * (psi_k0 + psi_k1 * M_k), 2 psi params per stage.
    No treatment-free model.

    theta layout (17 params):
      [0:6]    alpha1 = logit E[A1 | 1, L1, M1, A0, L0, M0]
      [6:9]    alpha0 = logit E[A0 | 1, L0, M0]
      [9:11]   psi1   = (psi1_intercept, psi1_M)
      [11:13]  beta1  = TF at stage 1 [1, L1]
      [13:15]  psi0   = (psi0_intercept, psi0_M)
      [15:17]  beta0  = TF at stage 0 [1, L0]
    """
    df = pd.read_csv(data_path)
    n = len(df)

    L0 = df["L0"].values
    M0 = df["M0"].values
    A0 = df["A0"].values.astype(float)
    L1 = df["L1"].values
    M1 = df["M1"].values
    A1 = df["A1"].values.astype(float)
    Y = df["Y"].values

    def stacked_ee(theta):
        alpha1 = theta[0:6]
        alpha0 = theta[6:9]
        psi1 = theta[9:11]
        beta1 = theta[11:13]
        psi0 = theta[13:15]
        beta0 = theta[15:17]

        # Treatment model stage 1: A1 ~ 1 + L1 + M1 + A0 + L0 + M0
        X1 = np.column_stack([np.ones(n), L1, M1, A0, L0, M0])
        p1 = expit(X1 @ alpha1)
        ee_alpha1 = ((A1 - p1)[:, None] * X1).T

        # Treatment model stage 0: A0 ~ 1 + L0 + M0
        X0 = np.column_stack([np.ones(n), L0, M0])
        p0 = expit(X0 @ alpha0)
        ee_alpha0 = ((A0 - p0)[:, None] * X0).T

        R1 = A1 - p1
        R0 = A0 - p0

        # Blip design: M_k = [1, M_k]
        BM1 = np.column_stack([np.ones(n), M1])
        BM0 = np.column_stack([np.ones(n), M0])

        # Stage 1: joint (beta1, psi1), pseudo-outcome = Y
        # gamma1 = A1 * (psi1[0] + psi1[1]*M1) = A1 * BM1 @ psi1
        Z1 = np.column_stack([np.ones(n), L1])
        AM1 = A1[:, None] * BM1
        RM1 = R1[:, None] * BM1
        resid1 = Y - Z1 @ beta1 - np.sum(AM1 * psi1[None, :], axis=1)
        ee_psi1 = (RM1.T * resid1[None, :])
        ee_beta1 = (Z1.T * resid1[None, :])

        # Backward transform: H0 = Y - gamma1 (blip only)
        gamma1 = np.sum(AM1 * psi1[None, :], axis=1)
        H0 = Y - gamma1

        # Stage 0: joint (beta0, psi0), pseudo-outcome = H0
        Z0 = np.column_stack([np.ones(n), L0])
        AM0 = A0[:, None] * BM0
        RM0 = R0[:, None] * BM0
        resid0 = H0 - Z0 @ beta0 - np.sum(AM0 * psi0[None, :], axis=1)
        ee_psi0 = (RM0.T * resid0[None, :])
        ee_beta0 = (Z0.T * resid0[None, :])

        return np.vstack([
            ee_alpha1, ee_alpha0,
            ee_psi1, ee_beta1,
            ee_psi0, ee_beta0
        ])

    from scipy.optimize import minimize
    def nll(b, Xd, yd):
        p = expit(Xd @ b)
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(yd * np.log(p) + (1 - yd) * np.log(1 - p))

    X1 = np.column_stack([np.ones(n), L1, M1, A0, L0, M0])
    X0 = np.column_stack([np.ones(n), L0, M0])
    init_a1 = minimize(nll, np.zeros(6), args=(X1, A1), method="BFGS").x
    init_a0 = minimize(nll, np.zeros(3), args=(X0, A0), method="BFGS").x

    init = np.concatenate([
        init_a1, init_a0,
        [2.0, 2.0],    # psi1 init
        [0.0, 0.0],    # beta1 init
        [1.0, 2.0],    # psi0 init
        [0.0, 0.0],    # beta0 init
    ])
    mest = MEstimator(stacked_ee, init=init)
    mest.estimate(solver="lm")

    psi1_int = mest.theta[9]
    psi1_M = mest.theta[10]
    psi0_int = mest.theta[13]
    psi0_M = mest.theta[14]
    se_psi1_int = np.sqrt(mest.variance[9, 9])
    se_psi1_M = np.sqrt(mest.variance[10, 10])
    se_psi0_int = np.sqrt(mest.variance[13, 13])
    se_psi0_M = np.sqrt(mest.variance[14, 14])

    return [
        {"parameter": "stage1_psi_intercept",
         "estimate": psi1_int, "se": se_psi1_int},
        {"parameter": "stage1_psi_M",
         "estimate": psi1_M, "se": se_psi1_M},
        {"parameter": "stage0_psi_intercept",
         "estimate": psi0_int, "se": se_psi0_int},
        {"parameter": "stage0_psi_M",
         "estimate": psi0_M, "se": se_psi0_M},
    ]


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    fixture_dir = os.path.join(
        script_dir, "..", "tests", "testthat", "fixtures"
    )

    scenarios = [
        {
            "name": "base (no EM, no TF)",
            "func": run_longitudinal_snm,
            "data": os.path.join(script_dir, "snm_longitudinal_fixture.csv"),
            "out": os.path.join(fixture_dir, "snm_longitudinal_delicatessen.csv"),
        },
        {
            "name": "TF (treatment-free ~L, no EM)",
            "func": run_longitudinal_snm_tf,
            "data": os.path.join(script_dir, "snm_longitudinal_fixture.csv"),
            "out": os.path.join(fixture_dir, "snm_longitudinal_tf_delicatessen.csv"),
        },
        {
            "name": "TV-EM (time-varying EM by M, with TF)",
            "func": run_longitudinal_snm_tv_em,
            "data": os.path.join(
                script_dir, "snm_longitudinal_tv_em_fixture.csv"
            ),
            "out": os.path.join(
                fixture_dir, "snm_longitudinal_tv_em_delicatessen.csv"
            ),
        },
    ]

    for sc in scenarios:
        print("=" * 60)
        print(f"Longitudinal SNM: {sc['name']}")
        print("=" * 60)

        results = sc["func"](sc["data"])

        for row in results:
            print(f"  {row['parameter']:30s} = {row['estimate']:.8f}"
                  f"  (SE = {row['se']:.8f})")

        with open(sc["out"], "w", newline="") as f:
            writer = csv.DictWriter(
                f, fieldnames=["parameter", "estimate", "se"])
            writer.writeheader()
            for row in results:
                writer.writerow({
                    "parameter": row["parameter"],
                    "estimate": f"{row['estimate']:.10f}",
                    "se": f"{row['se']:.10f}",
                })

        print(f"Wrote {sc['out']}\n")
