"""
Generate ICE g-computation reference values using delicatessen.

Implements the stacked M-estimation sandwich variance for ICE
(Zivich et al. 2024, Statistics in Medicine 43:5562-5572) using
delicatessen's MEstimator class.

Usage:
    cd data-raw
    python3 -m venv zepid_venv
    zepid_venv/bin/pip install delicatessen numpy pandas
    zepid_venv/bin/python zepid_reference.py

The fixture CSVs are generated by the R script in the test suite
(make_linear_scm, etc.) and must exist before running this script.

Output: prints reference values to paste into test-variance-reference.R.
"""

import numpy as np
import pandas as pd
from scipy.special import expit
from delicatessen import MEstimator
from delicatessen.estimating_equations import ee_regression


def ice_gcomp_2t(data, family_t1="gaussian",
                 a0_always=1, a1_always=1, a0_never=0, a1_never=0):
    """
    ICE g-computation for 2 time points with sandwich variance via
    delicatessen's stacked M-estimation.

    Parameters
    ----------
    data : DataFrame
        Wide-format data with columns A0, A1, L0, L1 (optional), Y.
    outcome_formula_t1, outcome_formula_t0 : str
        R-style formula strings (used to build design matrices).
    family_t1, family_t0 : str
        "gaussian" or "binomial".
    a0_always, a1_always, a0_never, a1_never : int/float
        Treatment values under "always" and "never" interventions.
    """
    n = len(data)
    Y = data["Y"].values
    A0 = data["A0"].values
    A1 = data["A1"].values
    L0 = data["L0"].values
    L1 = data["L1"].values if "L1" in data.columns else np.zeros(n)

    # Design matrices for model at t=1: Y ~ A1 + A0 + L1 + L0
    X1 = np.column_stack([np.ones(n), A1, A0, L1, L0])
    p1 = X1.shape[1]

    # Under intervention: replace A1 and A0
    X1_always = np.column_stack([np.ones(n), np.full(n, a1_always),
                                  np.full(n, a0_always), L1, L0])
    X1_never = np.column_stack([np.ones(n), np.full(n, a1_never),
                                 np.full(n, a0_never), L1, L0])

    # Design matrices for model at t=0: pseudo_Y ~ A0 + L0
    X0 = np.column_stack([np.ones(n), A0, L0])
    p0 = X0.shape[1]

    X0_always = np.column_stack([np.ones(n), np.full(n, a0_always), L0])
    X0_never = np.column_stack([np.ones(n), np.full(n, a0_never), L0])

    link1 = expit if family_t1 == "binomial" else lambda x: x
    link0_family = "binomial" if family_t1 == "binomial" else "gaussian"
    link0 = expit if link0_family == "binomial" else lambda x: x

    def psi(theta):
        # theta layout:
        # [0:p1]         = beta_1 (model at t=1)
        # [p1:p1+p0]     = beta_0 (model at t=0, always)
        # [p1+p0:p1+2*p0] = gamma_0 (model at t=0, never)
        # [p1+2*p0]      = mu_always
        # [p1+2*p0+1]    = mu_never
        beta1 = theta[0:p1]
        beta0_a = theta[p1:p1+p0]
        gamma0_n = theta[p1+p0:p1+2*p0]
        mu_a = theta[p1+2*p0]
        mu_n = theta[p1+2*p0+1]

        # Model at t=1: estimating equations
        eta1 = X1 @ beta1
        mu1 = link1(eta1)
        if family_t1 == "binomial":
            resid1 = (Y - mu1)
            ee1 = X1.T * resid1
        else:
            resid1 = Y - eta1
            ee1 = X1.T * resid1

        # Pseudo-outcomes under always
        eta1_a = X1_always @ beta1
        pseudo_a = link1(eta1_a)

        # Pseudo-outcomes under never
        eta1_n = X1_never @ beta1
        pseudo_n = link1(eta1_n)

        # Model at t=0 for always: pseudo_a ~ A0 + L0
        eta0_a = X0 @ beta0_a
        mu0_a = link0(eta0_a)
        if link0_family == "binomial":
            resid0_a = pseudo_a - mu0_a
            ee0_a = X0.T * resid0_a
        else:
            resid0_a = pseudo_a - eta0_a
            ee0_a = X0.T * resid0_a

        # Model at t=0 for never: pseudo_n ~ A0 + L0
        eta0_n = X0 @ gamma0_n
        mu0_n = link0(eta0_n)
        if link0_family == "binomial":
            resid0_n = pseudo_n - mu0_n
            ee0_n = X0.T * resid0_n
        else:
            resid0_n = pseudo_n - eta0_n
            ee0_n = X0.T * resid0_n

        # Final predictions under always
        eta_final_a = X0_always @ beta0_a
        pred_final_a = link0(eta_final_a)

        # Final predictions under never
        eta_final_n = X0_never @ gamma0_n
        pred_final_n = link0(eta_final_n)

        # Mean estimating equations
        ee_mu_a = pred_final_a - mu_a
        ee_mu_n = pred_final_n - mu_n

        return np.vstack([ee1, ee0_a, ee0_n,
                          ee_mu_a[np.newaxis, :],
                          ee_mu_n[np.newaxis, :]])

    # Initial values: OLS/logistic regression fits
    from numpy.linalg import lstsq
    if family_t1 == "binomial":
        from scipy.optimize import minimize
        def nll(b, X, y):
            p = expit(X @ b)
            p = np.clip(p, 1e-10, 1 - 1e-10)
            return -np.sum(y * np.log(p) + (1 - y) * np.log(1 - p))
        res1 = minimize(nll, np.zeros(p1), args=(X1, Y), method="BFGS")
        init_beta1 = res1.x
    else:
        init_beta1 = lstsq(X1, Y, rcond=None)[0]

    # Get pseudo-outcomes for initial beta0
    eta1_a_init = X1_always @ init_beta1
    pseudo_a_init = link1(eta1_a_init)
    eta1_n_init = X1_never @ init_beta1
    pseudo_n_init = link1(eta1_n_init)

    if link0_family == "binomial":
        res0_a = minimize(nll, np.zeros(p0), args=(X0, pseudo_a_init),
                          method="BFGS")
        init_beta0_a = res0_a.x
        res0_n = minimize(nll, np.zeros(p0), args=(X0, pseudo_n_init),
                          method="BFGS")
        init_gamma0_n = res0_n.x
    else:
        init_beta0_a = lstsq(X0, pseudo_a_init, rcond=None)[0]
        init_gamma0_n = lstsq(X0, pseudo_n_init, rcond=None)[0]

    eta_final_a_init = X0_always @ init_beta0_a
    mu_a_init = np.mean(link0(eta_final_a_init))
    eta_final_n_init = X0_never @ init_gamma0_n
    mu_n_init = np.mean(link0(eta_final_n_init))

    init = np.concatenate([init_beta1, init_beta0_a, init_gamma0_n,
                           [mu_a_init, mu_n_init]])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    params = mest.theta
    mu_always = params[p1+2*p0]
    mu_never = params[p1+2*p0+1]

    vcov = mest.variance
    se_always = np.sqrt(vcov[p1+2*p0, p1+2*p0])
    se_never = np.sqrt(vcov[p1+2*p0+1, p1+2*p0+1])

    ate = mu_always - mu_never
    var_ate = (vcov[p1+2*p0, p1+2*p0] +
               vcov[p1+2*p0+1, p1+2*p0+1] -
               2 * vcov[p1+2*p0, p1+2*p0+1])
    se_ate = np.sqrt(var_ate)

    return {
        "mu_always": mu_always, "se_always": se_always,
        "mu_never": mu_never, "se_never": se_never,
        "ate": ate, "se_ate": se_ate,
    }


def ice_gcomp_3t(data, family="gaussian"):
    """
    ICE g-computation for 3 time points with sandwich variance.
    """
    n = len(data)
    Y = data["Y"].values
    A0 = data["A0"].values
    A1 = data["A1"].values
    A2 = data["A2"].values
    L0 = data["L0"].values
    L1 = data["L1"].values
    L2 = data["L2"].values

    link = expit if family == "binomial" else lambda x: x
    link_family = "binomial" if family == "binomial" else "gaussian"

    # Model at t=2: Y ~ A2 + A1 + A0 + L2 + L1 + L0
    X2 = np.column_stack([np.ones(n), A2, A1, A0, L2, L1, L0])
    p2 = X2.shape[1]

    # Model at t=1: pseudo ~ A1 + A0 + L1 + L0
    X1 = np.column_stack([np.ones(n), A1, A0, L1, L0])
    p1 = X1.shape[1]

    # Model at t=0: pseudo ~ A0 + L0
    X0 = np.column_stack([np.ones(n), A0, L0])
    p0 = X0.shape[1]

    def make_X2_iv(a0, a1, a2):
        return np.column_stack([np.ones(n), np.full(n, a2),
                                 np.full(n, a1), np.full(n, a0),
                                 L2, L1, L0])

    def make_X1_iv(a0, a1):
        return np.column_stack([np.ones(n), np.full(n, a1),
                                 np.full(n, a0), L1, L0])

    def make_X0_iv(a0):
        return np.column_stack([np.ones(n), np.full(n, a0), L0])

    def psi(theta):
        idx = 0
        beta2 = theta[idx:idx+p2]; idx += p2

        # For each intervention, separate t=1 and t=0 models
        beta1_a = theta[idx:idx+p1]; idx += p1
        beta0_a = theta[idx:idx+p0]; idx += p0
        beta1_n = theta[idx:idx+p1]; idx += p1
        beta0_n = theta[idx:idx+p0]; idx += p0
        mu_a = theta[idx]; idx += 1
        mu_n = theta[idx]; idx += 1

        # EE for model at t=2
        eta2 = X2 @ beta2
        resid2 = Y - link(eta2)
        ee2 = X2.T * resid2

        # Always intervention
        pseudo2_a = link(make_X2_iv(1, 1, 1) @ beta2)
        eta1_a = X1 @ beta1_a
        resid1_a = pseudo2_a - link(eta1_a)
        ee1_a = X1.T * resid1_a

        pseudo1_a = link(make_X1_iv(1, 1) @ beta1_a)
        eta0_a = X0 @ beta0_a
        resid0_a = pseudo1_a - link(eta0_a)
        ee0_a = X0.T * resid0_a

        pred_final_a = link(make_X0_iv(1) @ beta0_a)
        ee_mu_a = pred_final_a - mu_a

        # Never intervention
        pseudo2_n = link(make_X2_iv(0, 0, 0) @ beta2)
        eta1_n = X1 @ beta1_n
        resid1_n = pseudo2_n - link(eta1_n)
        ee1_n = X1.T * resid1_n

        pseudo1_n = link(make_X1_iv(0, 0) @ beta1_n)
        eta0_n = X0 @ beta0_n
        resid0_n = pseudo1_n - link(eta0_n)
        ee0_n = X0.T * resid0_n

        pred_final_n = link(make_X0_iv(0) @ beta0_n)
        ee_mu_n = pred_final_n - mu_n

        return np.vstack([ee2, ee1_a, ee0_a, ee1_n, ee0_n,
                          ee_mu_a[np.newaxis, :],
                          ee_mu_n[np.newaxis, :]])

    from numpy.linalg import lstsq

    init_beta2 = lstsq(X2, Y, rcond=None)[0]

    pseudo2_a = link(make_X2_iv(1, 1, 1) @ init_beta2)
    pseudo2_n = link(make_X2_iv(0, 0, 0) @ init_beta2)

    init_beta1_a = lstsq(X1, pseudo2_a, rcond=None)[0]
    init_beta1_n = lstsq(X1, pseudo2_n, rcond=None)[0]

    pseudo1_a = link(make_X1_iv(1, 1) @ init_beta1_a)
    pseudo1_n = link(make_X1_iv(0, 0) @ init_beta1_n)

    init_beta0_a = lstsq(X0, pseudo1_a, rcond=None)[0]
    init_beta0_n = lstsq(X0, pseudo1_n, rcond=None)[0]

    mu_a_init = np.mean(link(make_X0_iv(1) @ init_beta0_a))
    mu_n_init = np.mean(link(make_X0_iv(0) @ init_beta0_n))

    init = np.concatenate([init_beta2, init_beta1_a, init_beta0_a,
                           init_beta1_n, init_beta0_n,
                           [mu_a_init, mu_n_init]])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    n_params = len(mest.theta)
    mu_always = mest.theta[n_params - 2]
    mu_never = mest.theta[n_params - 1]

    vcov = mest.variance
    se_always = np.sqrt(vcov[n_params-2, n_params-2])
    se_never = np.sqrt(vcov[n_params-1, n_params-1])

    ate = mu_always - mu_never
    var_ate = (vcov[n_params-2, n_params-2] +
               vcov[n_params-1, n_params-1] -
               2 * vcov[n_params-2, n_params-1])
    se_ate = np.sqrt(var_ate)

    return {
        "mu_always": mu_always, "se_always": se_always,
        "mu_never": mu_never, "se_never": se_never,
        "ate": ate, "se_ate": se_ate,
    }


def ice_gcomp_3t_binary(data):
    """
    ICE g-computation for 3 time points, binary outcome.
    """
    n = len(data)
    Y = data["Y"].values
    A0 = data["A0"].values
    A1 = data["A1"].values
    A2 = data["A2"].values
    L0 = data["L0"].values
    L1 = data["L1"].values
    L2 = data["L2"].values

    # Model at t=2: Y ~ A2 + A1 + A0 + L2 + L1 + L0 (binomial)
    X2 = np.column_stack([np.ones(n), A2, A1, A0, L2, L1, L0])
    p2 = X2.shape[1]

    # Model at t=1: pseudo ~ A1 + A0 + L1 + L0 (quasibinomial ≈ identity for EE)
    X1 = np.column_stack([np.ones(n), A1, A0, L1, L0])
    p1 = X1.shape[1]

    # Model at t=0: pseudo ~ A0 + L0
    X0 = np.column_stack([np.ones(n), A0, L0])
    p0 = X0.shape[1]

    def make_X2_iv(a0, a1, a2):
        return np.column_stack([np.ones(n), np.full(n, a2),
                                 np.full(n, a1), np.full(n, a0),
                                 L2, L1, L0])

    def make_X1_iv(a0, a1):
        return np.column_stack([np.ones(n), np.full(n, a1),
                                 np.full(n, a0), L1, L0])

    def make_X0_iv(a0):
        return np.column_stack([np.ones(n), np.full(n, a0), L0])

    def psi(theta):
        idx = 0
        beta2 = theta[idx:idx+p2]; idx += p2
        beta1_a = theta[idx:idx+p1]; idx += p1
        beta0_a = theta[idx:idx+p0]; idx += p0
        beta1_n = theta[idx:idx+p1]; idx += p1
        beta0_n = theta[idx:idx+p0]; idx += p0
        mu_a = theta[idx]; idx += 1
        mu_n = theta[idx]; idx += 1

        # Model at t=2 (binomial)
        mu2 = expit(X2 @ beta2)
        ee2 = X2.T * (Y - mu2)

        # Always: pseudo from t=2
        pseudo2_a = expit(make_X2_iv(1, 1, 1) @ beta2)
        # t=1 model for always (quasibinomial)
        mu1_a = expit(X1 @ beta1_a)
        ee1_a = X1.T * (pseudo2_a - mu1_a)

        pseudo1_a = expit(make_X1_iv(1, 1) @ beta1_a)
        mu0_a = expit(X0 @ beta0_a)
        ee0_a = X0.T * (pseudo1_a - mu0_a)

        pred_final_a = expit(make_X0_iv(1) @ beta0_a)
        ee_mu_a = pred_final_a - mu_a

        # Never: pseudo from t=2
        pseudo2_n = expit(make_X2_iv(0, 0, 0) @ beta2)
        mu1_n = expit(X1 @ beta1_n)
        ee1_n = X1.T * (pseudo2_n - mu1_n)

        pseudo1_n = expit(make_X1_iv(0, 0) @ beta1_n)
        mu0_n = expit(X0 @ beta0_n)
        ee0_n = X0.T * (pseudo1_n - mu0_n)

        pred_final_n = expit(make_X0_iv(0) @ beta0_n)
        ee_mu_n = pred_final_n - mu_n

        return np.vstack([ee2, ee1_a, ee0_a, ee1_n, ee0_n,
                          ee_mu_a[np.newaxis, :],
                          ee_mu_n[np.newaxis, :]])

    from numpy.linalg import lstsq
    from scipy.optimize import minimize

    def nll(b, X, y):
        p = expit(X @ b)
        p = np.clip(p, 1e-10, 1 - 1e-10)
        return -np.sum(y * np.log(p) + (1 - y) * np.log(1 - p))

    init_beta2 = minimize(nll, np.zeros(p2), args=(X2, Y), method="BFGS").x

    pseudo2_a = expit(make_X2_iv(1, 1, 1) @ init_beta2)
    pseudo2_n = expit(make_X2_iv(0, 0, 0) @ init_beta2)

    init_beta1_a = minimize(nll, np.zeros(p1), args=(X1, pseudo2_a), method="BFGS").x
    init_beta1_n = minimize(nll, np.zeros(p1), args=(X1, pseudo2_n), method="BFGS").x

    pseudo1_a = expit(make_X1_iv(1, 1) @ init_beta1_a)
    pseudo1_n = expit(make_X1_iv(0, 0) @ init_beta1_n)

    init_beta0_a = minimize(nll, np.zeros(p0), args=(X0, pseudo1_a), method="BFGS").x
    init_beta0_n = minimize(nll, np.zeros(p0), args=(X0, pseudo1_n), method="BFGS").x

    mu_a_init = np.mean(expit(make_X0_iv(1) @ init_beta0_a))
    mu_n_init = np.mean(expit(make_X0_iv(0) @ init_beta0_n))

    init = np.concatenate([init_beta2, init_beta1_a, init_beta0_a,
                           init_beta1_n, init_beta0_n,
                           [mu_a_init, mu_n_init]])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    n_params = len(mest.theta)
    mu_always = mest.theta[n_params - 2]
    mu_never = mest.theta[n_params - 1]

    vcov = mest.variance
    se_always = np.sqrt(vcov[n_params-2, n_params-2])
    se_never = np.sqrt(vcov[n_params-1, n_params-1])

    ate = mu_always - mu_never
    var_ate = (vcov[n_params-2, n_params-2] +
               vcov[n_params-1, n_params-1] -
               2 * vcov[n_params-2, n_params-1])
    se_ate = np.sqrt(var_ate)

    return {
        "mu_always": mu_always, "se_always": se_always,
        "mu_never": mu_never, "se_never": se_never,
        "ate": ate, "se_ate": se_ate,
    }


def ice_gcomp_2t_multi_conf(data):
    """
    ICE g-computation for 2 time points with multiple baseline confounders.
    Columns: A0, A1, L0a, L0b, L1, Y.
    """
    n = len(data)
    Y = data["Y"].values
    A0 = data["A0"].values
    A1 = data["A1"].values
    L0a = data["L0a"].values
    L0b = data["L0b"].values
    L1 = data["L1"].values

    # Model at t=1: Y ~ A1 + A0 + L1 + L0a + L0b
    X1 = np.column_stack([np.ones(n), A1, A0, L1, L0a, L0b])
    p1 = X1.shape[1]

    X1_always = np.column_stack([np.ones(n), np.ones(n), np.ones(n), L1, L0a, L0b])
    X1_never = np.column_stack([np.ones(n), np.zeros(n), np.zeros(n), L1, L0a, L0b])

    # Model at t=0: pseudo_Y ~ A0 + L0a + L0b
    X0 = np.column_stack([np.ones(n), A0, L0a, L0b])
    p0 = X0.shape[1]

    X0_always = np.column_stack([np.ones(n), np.ones(n), L0a, L0b])
    X0_never = np.column_stack([np.ones(n), np.zeros(n), L0a, L0b])

    def psi(theta):
        beta1 = theta[0:p1]
        beta0_a = theta[p1:p1+p0]
        gamma0_n = theta[p1+p0:p1+2*p0]
        mu_a = theta[p1+2*p0]
        mu_n = theta[p1+2*p0+1]

        resid1 = Y - X1 @ beta1
        ee1 = X1.T * resid1

        pseudo_a = X1_always @ beta1
        resid0_a = pseudo_a - X0 @ beta0_a
        ee0_a = X0.T * resid0_a

        pseudo_n = X1_never @ beta1
        resid0_n = pseudo_n - X0 @ gamma0_n
        ee0_n = X0.T * resid0_n

        pred_final_a = X0_always @ beta0_a
        ee_mu_a = pred_final_a - mu_a

        pred_final_n = X0_never @ gamma0_n
        ee_mu_n = pred_final_n - mu_n

        return np.vstack([ee1, ee0_a, ee0_n,
                          ee_mu_a[np.newaxis, :],
                          ee_mu_n[np.newaxis, :]])

    from numpy.linalg import lstsq

    init_beta1 = lstsq(X1, Y, rcond=None)[0]
    pseudo_a_init = X1_always @ init_beta1
    pseudo_n_init = X1_never @ init_beta1
    init_beta0_a = lstsq(X0, pseudo_a_init, rcond=None)[0]
    init_gamma0_n = lstsq(X0, pseudo_n_init, rcond=None)[0]
    mu_a_init = np.mean(X0_always @ init_beta0_a)
    mu_n_init = np.mean(X0_never @ init_gamma0_n)

    init = np.concatenate([init_beta1, init_beta0_a, init_gamma0_n,
                           [mu_a_init, mu_n_init]])

    mest = MEstimator(psi, init=init)
    mest.estimate(solver="lm")

    params = mest.theta
    mu_always = params[p1+2*p0]
    mu_never = params[p1+2*p0+1]
    vcov = mest.variance
    se_always = np.sqrt(vcov[p1+2*p0, p1+2*p0])
    se_never = np.sqrt(vcov[p1+2*p0+1, p1+2*p0+1])

    ate = mu_always - mu_never
    var_ate = (vcov[p1+2*p0, p1+2*p0] +
               vcov[p1+2*p0+1, p1+2*p0+1] -
               2 * vcov[p1+2*p0, p1+2*p0+1])
    se_ate = np.sqrt(var_ate)

    return {
        "mu_always": mu_always, "se_always": se_always,
        "mu_never": mu_never, "se_never": se_never,
        "ate": ate, "se_ate": se_ate,
    }


def long_to_wide(df):
    """Convert long-format causatr data to wide format."""
    times = sorted(df["time"].unique())
    n_times = len(times)
    ids = df[df["time"] == times[0]]["id"].values

    wide = pd.DataFrame({"id": ids})

    # Grab all L0* columns from the first time point
    first = df[df["time"] == times[0]].sort_values("id")
    for c in first.columns:
        if c.startswith("L0"):
            wide[c] = first[c].values

    for i, t in enumerate(times):
        sub = df[df["time"] == t].sort_values("id")
        wide[f"A{i}"] = sub["A"].values
        if "L" in sub.columns and i > 0:
            wide[f"L{i}"] = sub["L"].values
        if i == n_times - 1:
            wide["Y"] = sub["Y"].values

    return wide


if __name__ == "__main__":
    print("=" * 60)
    print("ICE g-computation reference values via delicatessen")
    print("Zivich et al. 2024, Statistics in Medicine 43:5562-5572")
    print("=" * 60)

    # --- Test case 1: Linear SCM, 2 timepoints ---
    print("\n--- Test case 1: Linear SCM, 2 timepoints ---")
    print("DGP: make_linear_scm(n=5000, n_times=2, seed=42)")
    print("True ATE = 3*2 - 1 = 5")

    df_long = pd.read_csv("ice_fixture_linear_2t.csv")
    df_wide = long_to_wide(df_long)

    res = ice_gcomp_2t(df_wide, family_t1="gaussian")
    print(f"  mu_always = {res['mu_always']:.4f}, se_always = {res['se_always']:.4f}")
    print(f"  mu_never  = {res['mu_never']:.4f}, se_never  = {res['se_never']:.4f}")
    print(f"  ate       = {res['ate']:.4f}, se_ate    = {res['se_ate']:.4f}")

    # --- Test case 2: Linear SCM, 3 timepoints ---
    print("\n--- Test case 2: Linear SCM, 3 timepoints ---")
    print("DGP: make_linear_scm(n=5000, n_times=3, seed=42)")
    print("True ATE = 3*3 - 1 = 8")

    df_long3 = pd.read_csv("ice_fixture_linear_3t.csv")
    df_wide3 = long_to_wide(df_long3)

    res3 = ice_gcomp_3t(df_wide3, family="gaussian")
    print(f"  mu_always = {res3['mu_always']:.4f}, se_always = {res3['se_always']:.4f}")
    print(f"  mu_never  = {res3['mu_never']:.4f}, se_never  = {res3['se_never']:.4f}")
    print(f"  ate       = {res3['ate']:.4f}, se_ate    = {res3['se_ate']:.4f}")

    # --- Test case 3: Binary outcome, 2 timepoints ---
    print("\n--- Test case 3: Binary outcome, 2 timepoints ---")
    print("DGP: Binary Y with treatment-confounder feedback, n=10000, seed=42")

    df_long_bin = pd.read_csv("ice_fixture_binary_2t.csv")
    df_wide_bin = long_to_wide(df_long_bin)

    res_bin = ice_gcomp_2t(df_wide_bin, family_t1="binomial")
    print(f"  mu_always = {res_bin['mu_always']:.4f}, se_always = {res_bin['se_always']:.4f}")
    print(f"  mu_never  = {res_bin['mu_never']:.4f}, se_never  = {res_bin['se_never']:.4f}")
    print(f"  rd        = {res_bin['ate']:.4f}, se_rd     = {res_bin['se_ate']:.4f}")

    # --- Test case 4: Binary outcome, 3 timepoints ---
    print("\n--- Test case 4: Binary outcome, 3 timepoints ---")
    print("DGP: Binary Y with 3-step feedback, n=8000, seed=42")

    df_long_bin3 = pd.read_csv("ice_fixture_binary_3t.csv")
    df_wide_bin3 = long_to_wide(df_long_bin3)

    res_bin3 = ice_gcomp_3t_binary(df_wide_bin3)
    print(f"  mu_always = {res_bin3['mu_always']:.4f}, se_always = {res_bin3['se_always']:.4f}")
    print(f"  mu_never  = {res_bin3['mu_never']:.4f}, se_never  = {res_bin3['se_never']:.4f}")
    print(f"  rd        = {res_bin3['ate']:.4f}, se_rd     = {res_bin3['se_ate']:.4f}")

    # --- Test case 5: Multiple baseline confounders ---
    print("\n--- Test case 5: Multiple baseline confounders, 2 timepoints ---")
    print("DGP: Continuous Y, 2 baseline confounders (L0a, L0b), n=8000, seed=42")

    df_long_mc = pd.read_csv("ice_fixture_multi_conf_2t.csv")
    df_wide_mc = long_to_wide(df_long_mc)

    res_mc = ice_gcomp_2t_multi_conf(df_wide_mc)
    print(f"  mu_always = {res_mc['mu_always']:.4f}, se_always = {res_mc['se_always']:.4f}")
    print(f"  mu_never  = {res_mc['mu_never']:.4f}, se_never  = {res_mc['se_never']:.4f}")
    print(f"  ate       = {res_mc['ate']:.4f}, se_ate    = {res_mc['se_ate']:.4f}")

    # --- R test snippet ---
    print("\n" + "=" * 60)
    print("Paste into test-variance-reference.R:")
    print("=" * 60)
    all_results = [("linear_2t", res), ("linear_3t", res3),
                   ("binary_2t", res_bin), ("binary_3t", res_bin3),
                   ("multi_conf_2t", res_mc)]
    for name, r in all_results:
        print(f"\n# {name}")
        print(f"ref_mu_always <- {r['mu_always']:.4f}")
        print(f"ref_se_always <- {r['se_always']:.4f}")
        print(f"ref_mu_never  <- {r['mu_never']:.4f}")
        print(f"ref_se_never  <- {r['se_never']:.4f}")
        print(f"ref_ate       <- {r['ate']:.4f}")
        print(f"ref_se_ate    <- {r['se_ate']:.4f}")
