# Cross-language validation: causatr vs delicatessen (Zivich et al. 2024).
#
# Reference values generated by data-raw/nhefs_delicatessen_reference.py,
# data-raw/ross_binary_reference.py, and data-raw/cole_transport_reference.py
# using delicatessen's stacked M-estimation sandwich.
#
# NHEFS examples replicate Hernán & Robins "Causal Inference: What If" (2025)
# Chapters 12-13. All use the bundled causatr::nhefs dataset.
# Design matrices match R's model.matrix() exactly (factor() dummy coding).

# -- Helpers ------------------------------------------------------------------

make_nhefs_cc <- function() {
  data("nhefs", package = "causatr", envir = environment())
  nhefs[nhefs$censored == 0 & !is.na(nhefs$education), ]
}

# Hernán & Robins confounders, Ch 12-13.
# The qsmk:smokeintensity interaction is outcome-specific — excluded from
# the propensity model via confounders_outcome / confounders_treatment.
nhefs_outcome_conf <- ~ sex +
  age +
  I(age^2) +
  race +
  factor(education) +
  smokeintensity +
  I(smokeintensity^2) +
  smokeyrs +
  I(smokeyrs^2) +
  factor(exercise) +
  factor(active) +
  wt71 +
  I(wt71^2) +
  qsmk:smokeintensity

nhefs_propensity_conf <- ~ sex +
  age +
  I(age^2) +
  race +
  factor(education) +
  smokeintensity +
  I(smokeintensity^2) +
  smokeyrs +
  I(smokeyrs^2) +
  factor(exercise) +
  factor(active) +
  wt71 +
  I(wt71^2)


# -- 1. NHEFS G-computation: exact SE match (Chapter 13) ---------------------

test_that("NHEFS g-comp matches delicatessen — ATE + SE", {
  nhefs_cc <- make_nhefs_cc()

  fit <- causat(
    nhefs_cc,
    outcome = "wt82_71",
    treatment = "qsmk",
    confounders = nhefs_outcome_conf
  )

  res <- contrast(
    fit,
    interventions = list(quit = static(1), cont = static(0)),
    reference = "cont",
    ci_method = "sandwich"
  )

  # delicatessen (nhefs_delicatessen_reference.py)
  expect_equal(res$contrasts$estimate[1], 3.5145, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], 0.4788, tolerance = 0.02)

  mu1 <- res$estimates$estimate[res$estimates$intervention == "quit"]
  mu0 <- res$estimates$estimate[res$estimates$intervention == "cont"]
  expect_equal(mu1, 5.2709, tolerance = 0.01)
  expect_equal(mu0, 1.7564, tolerance = 0.01)
})


# -- 2. NHEFS IPW Hájek: exact SE match (Chapter 12.2) -----------------------

test_that("NHEFS IPW matches delicatessen — ATE + SE", {
  nhefs_cc <- make_nhefs_cc()

  fit <- causat(
    nhefs_cc,
    outcome = "wt82_71",
    treatment = "qsmk",
    confounders_outcome = nhefs_outcome_conf,
    confounders_treatment = nhefs_propensity_conf,
    estimator = "ipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(quit = static(1), cont = static(0)),
    reference = "cont",
    ci_method = "sandwich"
  )

  # delicatessen: ATE = 3.4992, SE = 0.4902
  expect_equal(res$contrasts$estimate[1], 3.4992, tolerance = 0.02)
  expect_equal(res$contrasts$se[1], 0.4902, tolerance = 0.03)

  mu1 <- res$estimates$estimate[res$estimates$intervention == "quit"]
  mu0 <- res$estimates$estimate[res$estimates$intervention == "cont"]
  expect_equal(mu1, 5.2876, tolerance = 0.02)
  expect_equal(mu0, 1.7885, tolerance = 0.02)
})


# -- 3. NHEFS AIPW: exact SE match (Fine Point 13.2) -------------------------

test_that("NHEFS AIPW matches delicatessen — ATE + SE", {
  nhefs_cc <- make_nhefs_cc()

  fit <- causat(
    nhefs_cc,
    outcome = "wt82_71",
    treatment = "qsmk",
    confounders_outcome = nhefs_outcome_conf,
    confounders_treatment = nhefs_propensity_conf,
    estimator = "aipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(quit = static(1), cont = static(0)),
    reference = "cont",
    ci_method = "sandwich"
  )

  # delicatessen: ATE = 3.4861, SE = 0.4858
  expect_equal(res$contrasts$estimate[1], 3.4861, tolerance = 0.02)
  expect_equal(res$contrasts$se[1], 0.4858, tolerance = 0.03)

  mu1 <- res$estimates$estimate[res$estimates$intervention == "quit"]
  mu0 <- res$estimates$estimate[res$estimates$intervention == "cont"]
  expect_equal(mu1, 5.2628, tolerance = 0.02)
  expect_equal(mu0, 1.7767, tolerance = 0.02)
})


# -- 4. NHEFS IPW + effect modification by sex (Chapter 12.5) ----------------
#
# delicatessen MSM: Y ~ 1 + qsmk + sex + qsmk:sex
# qsmk = 3.5690 (SE 0.6329), qsmk:sex = -0.1389 (SE 1.0250)
# => ATE(sex=0) = 3.5690, ATE(sex=1) = 3.4301
#
# causatr's `by =` runs separate Hájek estimators per subgroup, giving
# subgroup-specific ATEs that can be compared to the MSM stratum-specific
# effects. The agreement is approximate since the MSM pools precision.

test_that("NHEFS IPW + EM by sex: subgroup ATEs bracket delicatessen MSM", {
  nhefs_cc <- make_nhefs_cc()

  fit <- causat(
    nhefs_cc,
    outcome = "wt82_71",
    treatment = "qsmk",
    confounders_outcome = nhefs_outcome_conf,
    confounders_treatment = nhefs_propensity_conf,
    estimator = "ipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(quit = static(1), cont = static(0)),
    reference = "cont",
    ci_method = "sandwich",
    by = "sex"
  )

  ate_sex0 <- res$contrasts$estimate[res$contrasts$by == "0"]
  ate_sex1 <- res$contrasts$estimate[res$contrasts$by == "1"]

  # Both subgroup ATEs should be in the range [2.5, 5.0] kg
  # (the interaction is small relative to the main effect)
  expect_gt(ate_sex0, 2.5)
  expect_lt(ate_sex0, 5.0)
  expect_gt(ate_sex1, 2.5)
  expect_lt(ate_sex1, 5.0)

  # delicatessen MSM overall qsmk coefficient ≈ 3.57
  # The weighted average of subgroup ATEs should be close
  n0 <- res$contrasts$n_by[res$contrasts$by == "0"]
  n1 <- res$contrasts$n_by[res$contrasts$by == "1"]
  pooled <- (ate_sex0 * n0 + ate_sex1 * n1) / (n0 + n1)
  expect_equal(pooled, 3.50, tolerance = 0.2)
})


# -- 5. NHEFS IPW + IPCW: exact SE match (Chapter 12.6) ----------------------

test_that("NHEFS IPW + IPCW matches delicatessen — ATE + SE", {
  data("nhefs", package = "causatr", envir = environment())
  nhefs_full <- nhefs[!is.na(nhefs$education), ]

  fit <- causat(
    nhefs_full,
    outcome = "wt82_71",
    treatment = "qsmk",
    confounders_outcome = nhefs_outcome_conf,
    confounders_treatment = nhefs_propensity_conf,
    confounders_censoring = nhefs_propensity_conf,
    estimator = "ipw",
    propensity_model_fn = stats::glm,
    censoring = "censored",
    ipcw = TRUE
  )

  res <- contrast(
    fit,
    interventions = list(quit = static(1), cont = static(0)),
    reference = "cont",
    ci_method = "sandwich"
  )

  # delicatessen: ATE = 3.5561, SE = 0.4925
  expect_equal(res$contrasts$estimate[1], 3.5561, tolerance = 0.1)
  expect_equal(res$contrasts$se[1], 0.4925, tolerance = 0.1)
})


# -- 6. Ross (2024): binary outcome, g-comp + IPW RD -------------------------
#
# DGP: W ~ Bern(0.5), X|W ~ Bern(expit(-1 + W)),
#       Y|X,W ~ Bern(expit(-2 + 0.1*X + 0.3*W)).
# True RD ≈ 0 (small treatment effect by design).
# Fixture: data-raw/ross_fixture_binary.csv, n = 3000, seed = 2024.

test_that("Ross binary g-comp matches delicatessen — RD + SE", {
  fixture <- read.csv(
    test_path("fixtures", "ross_fixture_binary.csv")
  )

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "X",
    confounders = ~W,
    family = stats::binomial()
  )

  res <- contrast(
    fit,
    interventions = list(x1 = static(1), x0 = static(0)),
    reference = "x0",
    ci_method = "sandwich"
  )

  # delicatessen (ross_binary_reference.py): RD = -0.0016, SE = 0.0131
  expect_equal(res$contrasts$estimate[1], -0.0016, tolerance = 0.005)
  expect_equal(res$contrasts$se[1], 0.0131, tolerance = 0.005)

  mu1 <- res$estimates$estimate[res$estimates$intervention == "x1"]
  mu0 <- res$estimates$estimate[res$estimates$intervention == "x0"]
  expect_equal(mu1, 0.1420, tolerance = 0.005)
  expect_equal(mu0, 0.1436, tolerance = 0.005)
})


test_that("Ross binary IPW matches delicatessen — RD + SE", {
  fixture <- read.csv(
    test_path("fixtures", "ross_fixture_binary.csv")
  )

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "X",
    confounders = ~W,
    estimator = "ipw",
    propensity_model_fn = stats::glm,
    family = stats::binomial()
  )

  res <- contrast(
    fit,
    interventions = list(x1 = static(1), x0 = static(0)),
    reference = "x0",
    ci_method = "sandwich"
  )

  # delicatessen: RD = -0.0059, SE = 0.0131
  expect_equal(res$contrasts$estimate[1], -0.0059, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], 0.0131, tolerance = 0.005)
})


# -- 7. Cole (2023): transportability via IOSW g-comp ------------------------
#
# DGP: Study (S=1) + target (S=0). Treatment randomized in study.
# Y = 3 + 2*A + 1*L1 + 0.5*L2 + N(0,1). True target ATE = 2.
# Fixture: data-raw/cole_fixture_transport.csv.

test_that("Cole transport g-comp matches delicatessen — ATE + SE", {
  fixture <- read.csv(
    test_path("fixtures", "cole_fixture_transport.csv")
  )

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "A",
    confounders = ~ L1 + L2,
    target = "S"
  )

  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  # delicatessen (cole_transport_reference.py): ATE = 2.1061, SE = 0.0652
  # SE tolerance widened: causatr's sandwich includes sampling-model
  # correction that delicatessen's simple g-comp formulation omits
  expect_equal(res$contrasts$estimate[1], 2.1061, tolerance = 0.05)
  expect_equal(res$contrasts$se[1], 0.0652, tolerance = 0.03)
})


test_that("Cole transport IPW matches delicatessen — ATE + SE", {
  fixture <- read.csv(
    test_path("fixtures", "cole_fixture_transport.csv")
  )

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "A",
    confounders = ~ L1 + L2,
    estimator = "ipw",
    propensity_model_fn = stats::glm,
    target = "S"
  )

  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  # delicatessen: ATE = 2.1083, SE = 0.0652
  # SE differs ~6% due to different sandwich correction for the
  # sampling model in IPW+transport (causatr propagates IOSW uncertainty
  # through Channel 2; delicatessen stacks propensity + sampling EEs)
  expect_equal(res$contrasts$estimate[1], 2.1083, tolerance = 0.05)
  expect_equal(res$contrasts$se[1], 0.0652, tolerance = 0.07)
})
