# Cross-validation of causatr variance estimators against external references:
#
# 1. stdReg2 comparison  — point-treatment sandwich vs independent implementation
# 2. Tightened bootstrap — sandwich ≈ bootstrap with large n, tight tolerance
# 3. Hand-computed SEs    — manual J V_β J' and delta method verification
# 4. ICE analytical       — ICE sandwich matches single-model sandwich (no feedback)
# 5. delicatessen refs    — ICE sandwich vs hard-coded values from Python
#
# Reference values in section 5 were generated by data-raw/zepid_reference.py
# using delicatessen (Zivich 2022) for stacked M-estimation sandwich variance.


# ── 1. stdReg2 comparison ────────────────────────────────────────────────────

test_that("gcomp sandwich matches stdReg2 — continuous outcome (DGP 1)", {
  df <- simulate_binary_continuous(n = 5000, seed = 123)

  fit <- causat(df, outcome = "Y", treatment = "A", confounders = ~L)
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  std_fit <- stdReg2::standardize_glm(
    Y ~ A + L,
    data = df,
    values = list(A = c(1, 0)),
    contrasts = "difference",
    reference = 0
  )
  std_res <- generics::tidy(std_fit)
  std_means <- std_res[std_res$contrast == "none", ]
  std_diff <- std_res[std_res$contrast == "difference" & std_res$A == 1, ]

  expect_equal(
    res$estimates$estimate[res$estimates$intervention == "a1"],
    std_means$Estimate[std_means$A == 1],
    tolerance = 1e-6
  )
  expect_equal(
    res$estimates$estimate[res$estimates$intervention == "a0"],
    std_means$Estimate[std_means$A == 0],
    tolerance = 1e-6
  )

  expect_equal(
    res$estimates$se[res$estimates$intervention == "a1"],
    std_means$Std.Error[std_means$A == 1],
    tolerance = 0.01
  )
  expect_equal(
    res$estimates$se[res$estimates$intervention == "a0"],
    std_means$Std.Error[std_means$A == 0],
    tolerance = 0.01
  )

  expect_equal(res$contrasts$estimate[1], std_diff$Estimate, tolerance = 1e-6)
  expect_equal(res$contrasts$se[1], std_diff$Std.Error, tolerance = 0.01)
})


test_that("gcomp sandwich matches stdReg2 — binary outcome, RD (DGP 2)", {
  df <- simulate_binary_binary(n = 5000, seed = 456)

  fit <- causat(
    df,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    family = binomial()
  )
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    type = "difference",
    ci_method = "sandwich"
  )

  std_fit <- stdReg2::standardize_glm(
    Y ~ A + L,
    data = df,
    family = "binomial",
    values = list(A = c(1, 0)),
    contrasts = "difference",
    reference = 0
  )
  std_res <- generics::tidy(std_fit)
  std_means <- std_res[std_res$contrast == "none", ]
  std_diff <- std_res[std_res$contrast == "difference" & std_res$A == 1, ]

  expect_equal(
    res$estimates$estimate[res$estimates$intervention == "a1"],
    std_means$Estimate[std_means$A == 1],
    tolerance = 1e-6
  )
  expect_equal(
    res$estimates$estimate[res$estimates$intervention == "a0"],
    std_means$Estimate[std_means$A == 0],
    tolerance = 1e-6
  )
  expect_equal(
    res$estimates$se[res$estimates$intervention == "a1"],
    std_means$Std.Error[std_means$A == 1],
    tolerance = 0.01
  )
  expect_equal(res$contrasts$se[1], std_diff$Std.Error, tolerance = 0.01)
})


test_that("gcomp sandwich matches stdReg2 — binary outcome, RR (DGP 2)", {
  df <- simulate_binary_binary(n = 5000, seed = 456)

  fit <- causat(
    df,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    family = binomial()
  )
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    type = "ratio",
    ci_method = "sandwich"
  )

  std_fit <- stdReg2::standardize_glm(
    Y ~ A + L,
    data = df,
    family = "binomial",
    values = list(A = c(1, 0)),
    contrasts = "ratio",
    reference = 0
  )
  std_res <- generics::tidy(std_fit)
  std_ratio <- std_res[std_res$contrast == "ratio" & std_res$A == 1, ]

  expect_equal(res$contrasts$estimate[1], std_ratio$Estimate, tolerance = 1e-6)

  causatr_se_log <- res$contrasts$se[1] / res$contrasts$estimate[1]
  std_z <- (log(std_ratio$upper.0.95) - log(std_ratio$lower.0.95)) / (2 * 1.96)
  expect_equal(causatr_se_log, std_z, tolerance = 0.05)
})


test_that("gcomp sandwich matches stdReg2 — NHEFS (Hernán & Robins)", {
  data("nhefs", package = "causatr")

  nhefs_cc <- nhefs[!is.na(nhefs$wt82_71) & !is.na(nhefs$education), ]

  confounders <- ~ sex + age + I(age^2) + race +
    factor(education) + smokeintensity + I(smokeintensity^2) +
    smokeyrs + I(smokeyrs^2) + factor(exercise) +
    factor(active) + wt71 + I(wt71^2) + qsmk:smokeintensity

  fit <- causat(
    nhefs_cc,
    outcome = "wt82_71",
    treatment = "qsmk",
    confounders = confounders
  )
  res <- contrast(
    fit,
    interventions = list(quit = static(1), cont = static(0)),
    reference = "cont",
    ci_method = "sandwich"
  )

  std_fit <- stdReg2::standardize_glm(
    wt82_71 ~ qsmk + sex + age + I(age^2) + race +
      factor(education) + smokeintensity + I(smokeintensity^2) +
      smokeyrs + I(smokeyrs^2) + factor(exercise) +
      factor(active) + wt71 + I(wt71^2) + qsmk:smokeintensity,
    data = nhefs_cc,
    values = list(qsmk = c(1, 0)),
    contrasts = "difference",
    reference = 0
  )
  std_res <- generics::tidy(std_fit)
  std_means <- std_res[std_res$contrast == "none", ]
  std_diff <- std_res[std_res$contrast == "difference" & std_res$qsmk == 1, ]

  expect_equal(
    res$estimates$estimate[res$estimates$intervention == "quit"],
    std_means$Estimate[std_means$qsmk == 1],
    tolerance = 1e-6
  )
  expect_equal(
    res$estimates$estimate[res$estimates$intervention == "cont"],
    std_means$Estimate[std_means$qsmk == 0],
    tolerance = 1e-6
  )
  expect_equal(
    res$estimates$se[res$estimates$intervention == "quit"],
    std_means$Std.Error[std_means$qsmk == 1],
    tolerance = 0.02
  )
  expect_equal(res$contrasts$se[1], std_diff$Std.Error, tolerance = 0.02)
})


# ── 2. Tightened bootstrap-sandwich agreement ────────────────────────────────

test_that("point gcomp: sandwich ≈ bootstrap within 15% (continuous, large n)", {
  skip_on_os("windows")
  df <- simulate_binary_continuous(n = 5000, seed = 700)

  fit <- causat(df, outcome = "Y", treatment = "A", confounders = ~L)

  res_sw <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )
  res_bt <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "bootstrap",
    n_boot = 300L,
    parallel = "multicore",
    ncpus = 2L
  )

  for (iv in c("a1", "a0")) {
    se_sw <- res_sw$estimates$se[res_sw$estimates$intervention == iv]
    se_bt <- res_bt$estimates$se[res_bt$estimates$intervention == iv]
    ratio <- se_bt / se_sw
    expect_gt(ratio, 0.85, label = paste(iv, "ratio lower"))
    expect_lt(ratio, 1.15, label = paste(iv, "ratio upper"))
  }

  ratio_c <- res_bt$contrasts$se[1] / res_sw$contrasts$se[1]
  expect_gt(ratio_c, 0.85)
  expect_lt(ratio_c, 1.15)
})


test_that("point gcomp: sandwich ≈ bootstrap within 15% (binary outcome)", {
  skip_on_os("windows")
  df <- simulate_binary_binary(n = 5000, seed = 701)

  fit <- causat(
    df,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    family = binomial()
  )

  res_sw <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )
  res_bt <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "bootstrap",
    n_boot = 300L,
    parallel = "multicore",
    ncpus = 2L
  )

  for (iv in c("a1", "a0")) {
    se_sw <- res_sw$estimates$se[res_sw$estimates$intervention == iv]
    se_bt <- res_bt$estimates$se[res_bt$estimates$intervention == iv]
    ratio <- se_bt / se_sw
    expect_gt(ratio, 0.85, label = paste(iv, "ratio lower"))
    expect_lt(ratio, 1.15, label = paste(iv, "ratio upper"))
  }
})


test_that("ICE: sandwich ≈ bootstrap within 20% (large n)", {
  skip_on_os("windows")
  long <- make_linear_scm(n = 5000, n_times = 2, seed = 702)

  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    confounders_tv = ~L,
    id = "id",
    time = "time"
  )

  res_sw <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    ci_method = "sandwich"
  )
  res_bt <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    ci_method = "bootstrap",
    n_boot = 200L,
    parallel = "multicore",
    ncpus = 2L
  )

  for (iv in c("always", "never")) {
    se_sw <- res_sw$estimates$se[res_sw$estimates$intervention == iv]
    se_bt <- res_bt$estimates$se[res_bt$estimates$intervention == iv]
    ratio <- se_bt / se_sw
    expect_gt(ratio, 0.80, label = paste(iv, "ratio lower"))
    expect_lt(ratio, 1.20, label = paste(iv, "ratio upper"))
  }

  ratio_c <- res_bt$contrasts$se[1] / res_sw$contrasts$se[1]
  expect_gt(ratio_c, 0.80)
  expect_lt(ratio_c, 1.20)
})


# ── 3. Hand-computed analytical SEs ──────────────────────────────────────────

test_that("sandwich vcov matches manual full IF — linear model", {
  set.seed(800)
  n <- 3000
  L <- rnorm(n)
  A <- rbinom(n, 1, plogis(0.5 * L))
  Y <- 2 + 3 * A + 1.5 * L + rnorm(n)
  df <- data.frame(Y = Y, A = A, L = L)

  fit <- causat(df, outcome = "Y", treatment = "A", confounders = ~L)
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  mod <- stats::glm(Y ~ A + L, data = df, family = gaussian())
  X <- model.matrix(mod)
  r <- residuals(mod, type = "response")
  beta <- coef(mod)

  XtWX_inv <- solve(crossprod(X))

  X_a1 <- X_a0 <- X
  X_a1[, "A"] <- 1
  X_a0[, "A"] <- 0

  preds_a1 <- as.numeric(X_a1 %*% beta)
  preds_a0 <- as.numeric(X_a0 %*% beta)
  mu_a1 <- mean(preds_a1)
  mu_a0 <- mean(preds_a0)

  g_a1 <- as.numeric(crossprod(X_a1, rep(1, n))) / n
  g_a0 <- as.numeric(crossprod(X_a0, rep(1, n))) / n

  h_a1 <- as.numeric(XtWX_inv %*% g_a1)
  h_a0 <- as.numeric(XtWX_inv %*% g_a0)

  IF_a1 <- (preds_a1 - mu_a1) + n * as.numeric(X %*% h_a1) * r
  IF_a0 <- (preds_a0 - mu_a0) + n * as.numeric(X %*% h_a0) * r

  vcov_manual <- matrix(0, 2, 2)
  vcov_manual[1, 1] <- sum(IF_a1^2) / n^2
  vcov_manual[2, 2] <- sum(IF_a0^2) / n^2
  vcov_manual[1, 2] <- vcov_manual[2, 1] <- sum(IF_a1 * IF_a0) / n^2

  expect_equal(
    as.numeric(vcov(res)),
    as.numeric(vcov_manual),
    tolerance = 1e-8
  )
})


test_that("sandwich vcov matches manual full IF — logistic model", {
  set.seed(801)
  n <- 3000
  L <- rnorm(n)
  A <- rbinom(n, 1, plogis(0.5 * L))
  Y <- rbinom(n, 1, plogis(-1 + 1.5 * A + 0.8 * L))
  df <- data.frame(Y = Y, A = A, L = L)

  fit <- causat(
    df,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    family = binomial()
  )
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  mod <- stats::glm(Y ~ A + L, data = df, family = binomial())
  X <- model.matrix(mod)
  r <- residuals(mod, type = "response")
  beta <- coef(mod)
  mu_eta <- mod$family$mu.eta(mod$linear.predictors)
  var_mu <- mod$family$variance(fitted(mod))
  w <- mu_eta^2 / var_mu

  XtWX_inv <- solve(crossprod(X, X * w))

  X_a1 <- X_a0 <- X
  X_a1[, "A"] <- 1
  X_a0[, "A"] <- 0

  preds_a1 <- plogis(as.numeric(X_a1 %*% beta))
  preds_a0 <- plogis(as.numeric(X_a0 %*% beta))
  mu_a1 <- mean(preds_a1)
  mu_a0 <- mean(preds_a0)

  eta_a1 <- as.numeric(X_a1 %*% beta)
  mu_eta_a1 <- plogis(eta_a1) * (1 - plogis(eta_a1))
  g_a1 <- as.numeric(crossprod(X_a1, mu_eta_a1)) / n

  eta_a0 <- as.numeric(X_a0 %*% beta)
  mu_eta_a0 <- plogis(eta_a0) * (1 - plogis(eta_a0))
  g_a0 <- as.numeric(crossprod(X_a0, mu_eta_a0)) / n

  h_a1 <- as.numeric(XtWX_inv %*% g_a1)
  h_a0 <- as.numeric(XtWX_inv %*% g_a0)

  IF_a1 <- (preds_a1 - mu_a1) + n * as.numeric(X %*% h_a1) * r
  IF_a0 <- (preds_a0 - mu_a0) + n * as.numeric(X %*% h_a0) * r

  vcov_manual <- matrix(0, 2, 2)
  vcov_manual[1, 1] <- sum(IF_a1^2) / n^2
  vcov_manual[2, 2] <- sum(IF_a0^2) / n^2
  vcov_manual[1, 2] <- vcov_manual[2, 1] <- sum(IF_a1 * IF_a0) / n^2

  expect_equal(
    as.numeric(vcov(res)),
    as.numeric(vcov_manual),
    tolerance = 1e-8
  )
})


test_that("ratio contrast SE matches manual delta method", {
  set.seed(802)
  n <- 5000
  L <- rnorm(n)
  A <- rbinom(n, 1, plogis(0.5 * L))
  Y <- rbinom(n, 1, plogis(-1 + 1.5 * A + 0.8 * L))
  df <- data.frame(Y = Y, A = A, L = L)

  fit <- causat(
    df,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    family = binomial()
  )
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    type = "ratio",
    ci_method = "sandwich"
  )

  mu_a1 <- res$estimates$estimate[res$estimates$intervention == "a1"]
  mu_a0 <- res$estimates$estimate[res$estimates$intervention == "a0"]
  V <- as.matrix(vcov(res))

  ratio_manual <- mu_a1 / mu_a0
  grad <- c(1 / mu_a0, -mu_a1 / mu_a0^2)
  se_ratio_manual <- sqrt(as.numeric(t(grad) %*% V %*% grad))
  se_log_manual <- se_ratio_manual / ratio_manual

  expect_equal(res$contrasts$estimate[1], ratio_manual, tolerance = 1e-10)
  expect_equal(res$contrasts$se[1], se_ratio_manual, tolerance = 1e-10)

  z <- qnorm(0.975)
  ci_lo_manual <- exp(log(ratio_manual) - z * se_log_manual)
  ci_hi_manual <- exp(log(ratio_manual) + z * se_log_manual)
  expect_equal(res$contrasts$ci_lower[1], ci_lo_manual, tolerance = 1e-10)
  expect_equal(res$contrasts$ci_upper[1], ci_hi_manual, tolerance = 1e-10)
})


test_that("OR contrast SE matches manual delta method", {
  set.seed(803)
  n <- 5000
  L <- rnorm(n)
  A <- rbinom(n, 1, plogis(0.5 * L))
  Y <- rbinom(n, 1, plogis(-1 + 1.5 * A + 0.8 * L))
  df <- data.frame(Y = Y, A = A, L = L)

  fit <- causat(
    df,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    family = binomial()
  )
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    type = "or",
    ci_method = "sandwich"
  )

  mu_a1 <- res$estimates$estimate[res$estimates$intervention == "a1"]
  mu_a0 <- res$estimates$estimate[res$estimates$intervention == "a0"]
  V <- as.matrix(vcov(res))

  or_manual <- (mu_a1 / (1 - mu_a1)) / (mu_a0 / (1 - mu_a0))
  grad <- c(
    or_manual / (mu_a1 * (1 - mu_a1)),
    -or_manual / (mu_a0 * (1 - mu_a0))
  )
  se_or_manual <- sqrt(as.numeric(t(grad) %*% V %*% grad))
  se_log_manual <- se_or_manual / or_manual

  expect_equal(res$contrasts$estimate[1], or_manual, tolerance = 1e-10)
  expect_equal(res$contrasts$se[1], se_or_manual, tolerance = 1e-10)

  z <- qnorm(0.975)
  ci_lo_manual <- exp(log(or_manual) - z * se_log_manual)
  ci_hi_manual <- exp(log(or_manual) + z * se_log_manual)
  expect_equal(res$contrasts$ci_lower[1], ci_lo_manual, tolerance = 1e-10)
  expect_equal(res$contrasts$ci_upper[1], ci_hi_manual, tolerance = 1e-10)
})


test_that("ATE SE >= V_beta[A,A] for linear model (full IF includes direct term)", {
  set.seed(804)
  n <- 3000
  L <- rnorm(n)
  A <- rbinom(n, 1, plogis(0.5 * L))
  Y <- 2 + 3 * A + 1.5 * L + rnorm(n)
  df <- data.frame(Y = Y, A = A, L = L)

  fit <- causat(df, outcome = "Y", treatment = "A", confounders = ~L)
  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  mod <- stats::glm(Y ~ A + L, data = df, family = gaussian())
  V_beta <- sandwich::sandwich(mod)

  ate_from_model <- unname(coef(mod)["A"])
  ate_from_causatr <- res$contrasts$estimate[1]
  expect_equal(ate_from_causatr, ate_from_model, tolerance = 1e-10)

  se_param_only <- sqrt(V_beta["A", "A"])
  se_full_if <- res$contrasts$se[1]
  expect_true(se_full_if >= se_param_only * 0.99)
})


# ── 4. ICE sandwich: analytical cross-validation ────────────────────────────

test_that("ICE sandwich matches single-model sandwich when no feedback", {
  set.seed(900)
  n <- 5000
  L0 <- rnorm(n)
  A0 <- rbinom(n, 1, 0.5)
  A1 <- rbinom(n, 1, 0.5)
  Y <- 2 + 3 * A0 + 1.5 * A1 + L0 + rnorm(n)

  long <- rbind(
    data.frame(id = 1:n, time = 0L, A = A0, L0 = L0, Y = NA_real_),
    data.frame(id = 1:n, time = 1L, A = A1, L0 = L0, Y = Y)
  )

  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    id = "id",
    time = "time"
  )
  res_ice <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  wide <- data.frame(A0 = A0, A1 = A1, L0 = L0, Y = Y)
  mod <- stats::glm(Y ~ A0 + A1 + L0, data = wide, family = gaussian())
  V_single <- sandwich::sandwich(mod)
  beta <- coef(mod)

  L0bar <- mean(L0)
  J <- rbind(
    always = c(1, 1, 1, L0bar),
    never = c(1, 0, 0, L0bar)
  )
  vcov_single <- J %*% V_single %*% t(J)

  mu_always_ref <- unname(beta[1] + beta[2] + beta[3] + beta[4] * L0bar)
  mu_never_ref <- unname(beta[1] + beta[4] * L0bar)
  expect_equal(
    res_ice$estimates$estimate[res_ice$estimates$intervention == "always"],
    mu_always_ref,
    tolerance = 0.05
  )
  expect_equal(
    res_ice$estimates$estimate[res_ice$estimates$intervention == "never"],
    mu_never_ref,
    tolerance = 0.05
  )

  se_always_ref <- sqrt(vcov_single["always", "always"])
  se_never_ref <- sqrt(vcov_single["never", "never"])
  expect_equal(
    res_ice$estimates$se[res_ice$estimates$intervention == "always"],
    se_always_ref,
    tolerance = 0.10
  )
  expect_equal(
    res_ice$estimates$se[res_ice$estimates$intervention == "never"],
    se_never_ref,
    tolerance = 0.10
  )

  ate_se_ref <- sqrt(
    vcov_single["always", "always"] +
      vcov_single["never", "never"] -
      2 * vcov_single["always", "never"]
  )
  expect_equal(res_ice$contrasts$se[1], ate_se_ref, tolerance = 0.10)
})


test_that("ICE sandwich matches single-model sandwich — binary outcome", {
  set.seed(901)
  n <- 5000
  L0 <- rnorm(n)
  A0 <- rbinom(n, 1, 0.5)
  A1 <- rbinom(n, 1, 0.5)
  Y <- rbinom(n, 1, plogis(-1 + 1.5 * A0 + A1 + 0.5 * L0))

  long <- rbind(
    data.frame(id = 1:n, time = 0L, A = A0, L0 = L0, Y = NA_real_),
    data.frame(id = 1:n, time = 1L, A = A1, L0 = L0, Y = Y)
  )

  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    id = "id",
    time = "time",
    family = binomial()
  )
  res_ice <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  wide <- data.frame(A0 = A0, A1 = A1, L0 = L0, Y = Y)
  mod <- stats::glm(Y ~ A0 + A1 + L0, data = wide, family = binomial())
  V_single <- sandwich::sandwich(mod)
  beta <- coef(mod)

  X <- model.matrix(~ A0 + A1 + L0, data = wide)
  X_always <- X_never <- X
  X_always[, "A0"] <- 1
  X_always[, "A1"] <- 1
  X_never[, "A0"] <- 0
  X_never[, "A1"] <- 0

  eta_always <- as.numeric(X_always %*% beta)
  mu_eta_always <- plogis(eta_always) * (1 - plogis(eta_always))
  J_always <- as.numeric(crossprod(X_always, mu_eta_always)) / n

  eta_never <- as.numeric(X_never %*% beta)
  mu_eta_never <- plogis(eta_never) * (1 - plogis(eta_never))
  J_never <- as.numeric(crossprod(X_never, mu_eta_never)) / n

  J <- rbind(always = J_always, never = J_never)
  vcov_single <- J %*% V_single %*% t(J)

  se_always_ref <- sqrt(vcov_single["always", "always"])
  se_never_ref <- sqrt(vcov_single["never", "never"])
  expect_equal(
    res_ice$estimates$se[res_ice$estimates$intervention == "always"],
    se_always_ref,
    tolerance = 0.15
  )
  expect_equal(
    res_ice$estimates$se[res_ice$estimates$intervention == "never"],
    se_never_ref,
    tolerance = 0.15
  )
})


# ── 5. delicatessen reference values (ICE) ──────────────────────────────────
#
# Reference values generated by data-raw/zepid_reference.py using
# delicatessen (Zivich 2022) stacked M-estimation sandwich variance.
# Zivich PN et al. (2024). Statistics in Medicine 43:5562-5572.

test_that("ICE sandwich matches delicatessen — linear SCM, 2 timepoints", {
  ref_mu_always <- 14.9858
  ref_se_always <- 0.0334
  ref_mu_never <- 9.9794
  ref_se_never <- 0.0340
  ref_ate <- 5.0063
  ref_se_ate <- 0.0414

  long <- make_linear_scm(n = 5000, n_times = 2, seed = 42)
  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    confounders_tv = ~L,
    id = "id",
    time = "time"
  )
  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  mu_always <- res$estimates$estimate[res$estimates$intervention == "always"]
  mu_never <- res$estimates$estimate[res$estimates$intervention == "never"]

  expect_equal(mu_always, ref_mu_always, tolerance = 0.01)
  expect_equal(mu_never, ref_mu_never, tolerance = 0.01)
  expect_equal(res$contrasts$estimate[1], ref_ate, tolerance = 0.01)

  se_always <- res$estimates$se[res$estimates$intervention == "always"]
  se_never <- res$estimates$se[res$estimates$intervention == "never"]

  expect_equal(se_always, ref_se_always, tolerance = 0.01)
  expect_equal(se_never, ref_se_never, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], ref_se_ate, tolerance = 0.01)
})


test_that("ICE sandwich matches delicatessen — linear SCM, 3 timepoints", {
  ref_mu_always <- 17.9551
  ref_se_always <- 0.0418
  ref_mu_never <- 10.0097
  ref_se_never <- 0.0439
  ref_ate <- 7.9454
  ref_se_ate <- 0.0537

  long <- make_linear_scm(n = 5000, n_times = 3, seed = 42)
  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    confounders_tv = ~L,
    id = "id",
    time = "time",
    history = Inf
  )
  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  mu_always <- res$estimates$estimate[res$estimates$intervention == "always"]
  mu_never <- res$estimates$estimate[res$estimates$intervention == "never"]

  expect_equal(mu_always, ref_mu_always, tolerance = 0.01)
  expect_equal(mu_never, ref_mu_never, tolerance = 0.01)
  expect_equal(res$contrasts$estimate[1], ref_ate, tolerance = 0.01)

  se_always <- res$estimates$se[res$estimates$intervention == "always"]
  se_never <- res$estimates$se[res$estimates$intervention == "never"]

  expect_equal(se_always, ref_se_always, tolerance = 0.01)
  expect_equal(se_never, ref_se_never, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], ref_se_ate, tolerance = 0.01)
})


test_that("ICE sandwich matches delicatessen — binary outcome, 2 timepoints", {
  ref_mu_always <- 0.4780
  ref_se_always <- 0.0082
  ref_mu_never <- 0.1347
  ref_se_never <- 0.0057
  ref_rd <- 0.3433
  ref_se_rd <- 0.0113

  set.seed(42)
  n <- 10000
  L0 <- rnorm(n)
  A0 <- rbinom(n, 1, plogis(0.5 * L0))
  L1 <- A0 + 0.5 * L0 + rnorm(n, 0, 0.5)
  A1 <- rbinom(n, 1, plogis(0.3 * L1 + 0.2 * A0))
  Y <- rbinom(n, 1, plogis(-2 + 0.8 * A0 + 0.8 * A1 + 0.5 * L0 + 0.3 * L1))

  long <- rbind(
    data.frame(
      id = 1:n, time = 0L, A = A0,
      L = NA_real_, L0 = L0, Y = NA_real_
    ),
    data.frame(id = 1:n, time = 1L, A = A1, L = L1, L0 = L0, Y = Y)
  )

  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    confounders_tv = ~L,
    id = "id",
    time = "time",
    family = binomial()
  )
  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  mu_always <- res$estimates$estimate[res$estimates$intervention == "always"]
  mu_never <- res$estimates$estimate[res$estimates$intervention == "never"]

  expect_equal(mu_always, ref_mu_always, tolerance = 0.005)
  expect_equal(mu_never, ref_mu_never, tolerance = 0.005)
  expect_equal(res$contrasts$estimate[1], ref_rd, tolerance = 0.005)

  se_always <- res$estimates$se[res$estimates$intervention == "always"]
  se_never <- res$estimates$se[res$estimates$intervention == "never"]

  expect_equal(se_always, ref_se_always, tolerance = 0.01)
  expect_equal(se_never, ref_se_never, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], ref_se_rd, tolerance = 0.01)
})


test_that("ICE sandwich matches delicatessen — binary outcome, 3 timepoints", {
  ref_mu_always <- 0.4146
  ref_se_always <- 0.0103
  ref_mu_never <- 0.0977
  ref_se_never <- 0.0060
  ref_rd <- 0.3169
  ref_se_rd <- 0.0141

  set.seed(42)
  n <- 8000
  L0 <- rnorm(n)
  A0 <- rbinom(n, 1, plogis(0.5 * L0))
  L1 <- A0 + 0.5 * L0 + rnorm(n, 0, 0.5)
  A1 <- rbinom(n, 1, plogis(0.3 * L1 + 0.2 * A0))
  L2 <- A1 + 0.3 * L1 + 0.5 * L0 + rnorm(n, 0, 0.5)
  A2 <- rbinom(n, 1, plogis(0.3 * L2 + 0.2 * A1))
  Y <- rbinom(
    n, 1,
    plogis(-2.5 + 0.6 * A0 + 0.6 * A1 + 0.6 * A2 +
      0.4 * L0 + 0.2 * L1 + 0.2 * L2)
  )

  long <- rbind(
    data.frame(id = 1:n, time = 0L, A = A0, L = NA_real_, L0 = L0, Y = NA_real_),
    data.frame(id = 1:n, time = 1L, A = A1, L = L1, L0 = L0, Y = NA_real_),
    data.frame(id = 1:n, time = 2L, A = A2, L = L2, L0 = L0, Y = Y)
  )

  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~L0,
    confounders_tv = ~L,
    id = "id",
    time = "time",
    family = binomial(),
    history = Inf
  )
  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  mu_always <- res$estimates$estimate[res$estimates$intervention == "always"]
  mu_never <- res$estimates$estimate[res$estimates$intervention == "never"]

  expect_equal(mu_always, ref_mu_always, tolerance = 0.005)
  expect_equal(mu_never, ref_mu_never, tolerance = 0.005)
  expect_equal(res$contrasts$estimate[1], ref_rd, tolerance = 0.005)

  se_always <- res$estimates$se[res$estimates$intervention == "always"]
  se_never <- res$estimates$se[res$estimates$intervention == "never"]

  expect_equal(se_always, ref_se_always, tolerance = 0.01)
  expect_equal(se_never, ref_se_never, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], ref_se_rd, tolerance = 0.01)
})


test_that("ICE sandwich matches delicatessen — multiple baseline confounders", {
  ref_mu_always <- 11.0165
  ref_se_always <- 0.0278
  ref_mu_never <- 5.4040
  ref_se_never <- 0.0299
  ref_ate <- 5.6125
  ref_se_ate <- 0.0327

  set.seed(42)
  n <- 8000
  L0a <- rnorm(n)
  L0b <- rbinom(n, 1, 0.4)
  A0 <- rbinom(n, 1, plogis(0.8 * L0a + 0.5 * L0b))
  L1 <- 0.7 * A0 + 0.3 * L0a + 0.2 * L0b + rnorm(n, 0, 0.5)
  A1 <- rbinom(n, 1, plogis(0.4 * L1 + 0.3 * A0 + 0.2 * L0b))
  Y <- 5 + 2.5 * A0 + 2.5 * A1 + 1.5 * L0a + L0b + 0.8 * L1 + rnorm(n)

  long <- rbind(
    data.frame(
      id = 1:n, time = 0L, A = A0,
      L = NA_real_, L0a = L0a, L0b = L0b, Y = NA_real_
    ),
    data.frame(
      id = 1:n, time = 1L, A = A1,
      L = L1, L0a = L0a, L0b = L0b, Y = Y
    )
  )

  fit <- causat(
    long,
    outcome = "Y",
    treatment = "A",
    confounders = ~ L0a + L0b,
    confounders_tv = ~L,
    id = "id",
    time = "time"
  )
  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  mu_always <- res$estimates$estimate[res$estimates$intervention == "always"]
  mu_never <- res$estimates$estimate[res$estimates$intervention == "never"]

  expect_equal(mu_always, ref_mu_always, tolerance = 0.01)
  expect_equal(mu_never, ref_mu_never, tolerance = 0.01)
  expect_equal(res$contrasts$estimate[1], ref_ate, tolerance = 0.01)

  se_always <- res$estimates$se[res$estimates$intervention == "always"]
  se_never <- res$estimates$se[res$estimates$intervention == "never"]

  expect_equal(se_always, ref_se_always, tolerance = 0.01)
  expect_equal(se_never, ref_se_never, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], ref_se_ate, tolerance = 0.01)
})
