# Extended delicatessen cross-checks: categorical AIPW and longitudinal AIPW.
#
# Reference values generated by data-raw/aipw_categorical_reference.py and
# data-raw/aipw_longitudinal_reference.py using the delicatessen stacked
# M-estimation sandwich (Zivich et al. 2024). Fixture CSVs ensure identical
# data across R and Python.

# -- Categorical AIPW: 3-arm treatment, ATE(b-a) and ATE(c-a) ---------------
#
# DGP: L ~ N(0,1), A ~ Multinomial(softmax(0, 0.3+0.5L, -0.2+0.3L)),
#       Y = 2 + 3*I(b) + 5*I(c) + 1.5*L + N(0,1).
# True ATE(b-a) = 3, ATE(c-a) = 5.

test_that("Categorical AIPW SE matches delicatessen — ATE(b vs a)", {
  fixture <- read.csv(
    test_path("..", "..", "data-raw", "aipw_fixture_categorical.csv"),
    stringsAsFactors = FALSE
  )
  fixture$A <- factor(fixture$A, levels = c("a", "b", "c"))

  # delicatessen reference (data-raw/aipw_categorical_reference.py)
  ref_ate_ba <- 3.0220
  ref_se_ba <- 0.0343

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    estimator = "aipw"
  )

  res <- contrast(
    fit,
    interventions = list(set_b = static("b"), set_a = static("a")),
    reference = "set_a",
    ci_method = "sandwich"
  )

  expect_equal(res$contrasts$estimate[1], ref_ate_ba, tolerance = 0.05)
  expect_equal(res$contrasts$se[1], ref_se_ba, tolerance = 0.01)
})


test_that("Categorical AIPW SE matches delicatessen — ATE(c vs a)", {
  fixture <- read.csv(
    test_path("..", "..", "data-raw", "aipw_fixture_categorical.csv"),
    stringsAsFactors = FALSE
  )
  fixture$A <- factor(fixture$A, levels = c("a", "b", "c"))

  # delicatessen reference
  ref_ate_ca <- 5.0299
  ref_se_ca <- 0.0389

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    estimator = "aipw"
  )

  res <- contrast(
    fit,
    interventions = list(set_c = static("c"), set_a = static("a")),
    reference = "set_a",
    ci_method = "sandwich"
  )

  expect_equal(res$contrasts$estimate[1], ref_ate_ca, tolerance = 0.05)
  expect_equal(res$contrasts$se[1], ref_se_ca, tolerance = 0.01)
})


# -- Binary IPW: point treatment, ATE(1 vs 0) ---------------------------------
#
# DGP: L ~ N(0,1), A ~ Bern(expit(0.5L)), Y = 2 + 3A + 1.5L + N(0,1).
# True ATE = 3. n = 2000, seed = 42.
# Propensity: Z = [1, L], standard logistic.

test_that("Binary IPW SE matches delicatessen — ATE", {
  fixture <- read.csv(
    test_path("..", "..", "data-raw", "ipw_fixture_binary.csv")
  )

  # delicatessen reference (data-raw/ipw_binary_reference.py)
  ref_ate <- 2.9927
  ref_se_ate <- 0.0473

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    estimator = "ipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  expect_equal(res$contrasts$estimate[1], ref_ate, tolerance = 0.01)
  expect_equal(res$contrasts$se[1], ref_se_ate, tolerance = 0.005)
})


test_that("Binary IPW counterfactual means match delicatessen", {
  fixture <- read.csv(
    test_path("..", "..", "data-raw", "ipw_fixture_binary.csv")
  )

  # delicatessen reference
  ref_mu1 <- 4.9228
  ref_se_mu1 <- 0.0496
  ref_mu0 <- 1.9301
  ref_se_mu0 <- 0.0472

  fit <- causat(
    fixture,
    outcome = "Y",
    treatment = "A",
    confounders = ~L,
    estimator = "ipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(a1 = static(1), a0 = static(0)),
    reference = "a0",
    ci_method = "sandwich"
  )

  mu1 <- res$estimates$estimate[res$estimates$intervention == "a1"]
  mu0 <- res$estimates$estimate[res$estimates$intervention == "a0"]
  se1 <- res$estimates$se[res$estimates$intervention == "a1"]
  se0 <- res$estimates$se[res$estimates$intervention == "a0"]

  expect_equal(mu1, ref_mu1, tolerance = 0.01)
  expect_equal(mu0, ref_mu0, tolerance = 0.01)
  expect_equal(se1, ref_se_mu1, tolerance = 0.005)
  expect_equal(se0, ref_se_mu0, tolerance = 0.005)
})


# -- Longitudinal IPW: 2-period, ATE(always vs never) -------------------------
#
# DGP: Naimi-inspired with treatment-confounder feedback (see
# data-raw/ipw_longitudinal_reference.py for full specification).
# True ATE ≈ 100 (2 × 50 from both treatment periods).
# Propensity specs match causatr: t=0 uses [1, Ltv, age],
# t=1 uses [1, Ltv, lag1_A, lag1_Ltv, age].

test_that("Longitudinal IPW ATE matches delicatessen — always vs never", {
  fixture_wide <- read.csv(
    test_path("..", "..", "data-raw", "aipw_fixture_longitudinal.csv")
  )

  # delicatessen reference (data-raw/ipw_longitudinal_reference.py)
  ref_ate <- 104.4203
  ref_se_ate <- 1.6358

  n <- nrow(fixture_wide)
  d <- data.frame(
    id = rep(seq_len(n), each = 2),
    time = rep(0:1, n),
    A = as.vector(rbind(fixture_wide$A0, fixture_wide$A1)),
    Ltv = as.vector(rbind(fixture_wide$Ltv0, fixture_wide$Ltv1)),
    age = rep(fixture_wide$age, each = 2),
    Y = rep(fixture_wide$Y, each = 2)
  )

  fit <- causat(
    d,
    outcome = "Y",
    treatment = "A",
    confounders = ~age,
    confounders_tv = ~Ltv,
    id = "id",
    time = "time",
    estimator = "ipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  expect_equal(res$contrasts$estimate[1], ref_ate, tolerance = 0.5)
  expect_equal(res$contrasts$se[1], ref_se_ate, tolerance = 0.2)
})


test_that("Longitudinal IPW counterfactual means match delicatessen", {
  fixture_wide <- read.csv(
    test_path("..", "..", "data-raw", "aipw_fixture_longitudinal.csv")
  )

  # delicatessen reference (data-raw/ipw_longitudinal_reference.py)
  ref_mu_always <- 397.1909
  ref_mu_never <- 292.7706

  n <- nrow(fixture_wide)
  d <- data.frame(
    id = rep(seq_len(n), each = 2),
    time = rep(0:1, n),
    A = as.vector(rbind(fixture_wide$A0, fixture_wide$A1)),
    Ltv = as.vector(rbind(fixture_wide$Ltv0, fixture_wide$Ltv1)),
    age = rep(fixture_wide$age, each = 2),
    Y = rep(fixture_wide$Y, each = 2)
  )

  fit <- causat(
    d,
    outcome = "Y",
    treatment = "A",
    confounders = ~age,
    confounders_tv = ~Ltv,
    id = "id",
    time = "time",
    estimator = "ipw",
    propensity_model_fn = stats::glm
  )

  res <- contrast(
    fit,
    interventions = list(always = static(1), never = static(0)),
    reference = "never",
    ci_method = "sandwich"
  )

  # ATE = mu_always - mu_never
  expect_equal(
    res$contrasts$estimate[1],
    ref_mu_always - ref_mu_never,
    tolerance = 0.5
  )
})
